### ISSUE TITLE
minimap-color-highlight

### ISSUE THREAD

**Issue by plttn** [abe33/atom-pigments#10]
Does that plugin support pigments just yet (or will pigments include a minimap binding in the near future)?

**Comment by abe33** [comment]
I had planned to create a `minimap-pigments` plugin, the pigments API is a bit different than the `atom-color-highlight` one so I think it'll be better as two separate plugin. But be reassured it'll come at some point, I'm waiting a bit so that pigments performance got better.

**Comment by abe33** [comment]
I forgot to update this issue, [minimap-pigments](http://atom.io/packages/minimap-pigments) is out ;)
