### ISSUE TITLE
upgarde to v0.17.1 fails

### ISSUE THREAD

**Issue by pgnd** [abe33/atom-pigments#101]
Updating to “pigments@0.17.1” failed.Hide output…

    npm ERR! not a package /tmp/d-115913-4679-7xi961/package.tgz
    npm ERR! addLocal Could not install /tmp/d-115913-4679-7xi961/package.tgz
    npm ERR! Linux 4.2.3-1.gef1562d-default
    npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/pgnd/.atom/.apm/.apmrc" "--userconfig" "/home/pgnd/.atom/.apmrc" "install" "/tmp/d-115913-4679-7xi961/package.tgz" "--target=0.30.7" "--arch=x64"
    npm ERR! node v0.10.40
    npm ERR! npm  v2.13.3
    npm ERR! path /tmp/npm-4762-a851eb6b/unpack-a4469f208e73/package.json
    npm ERR! code ENOENT
    npm ERR! errno 34

    npm ERR! enoent ENOENT, open '/tmp/npm-4762-a851eb6b/unpack-a4469f208e73/package.json'
    npm ERR! enoent This is most likely not a problem with npm itself
    npm ERR! enoent and is related to npm not being able to find a file.
    npm ERR! enoent 

    npm ERR! Please include the following file with any support request:
    npm ERR!     /tmp/apm-install-dir-115913-4679-pb9cno/npm-debug.log

    ls -al \
    /tmp/npm-4762-a851eb6b/unpack-a4469f208e73/package.json \
    /tmp/apm-install-dir-115913-4679-pb9cno/npm-debug.log
        ls: cannot access /tmp/npm-4762-a851eb6b/unpack-a4469f208e73/package.json: No such file or directory
        ls: cannot access /tmp/apm-install-dir-115913-4679-pb9cno/npm-debug.log: No such file or directory

**Comment by abe33** [comment]
Probably just a network issue when downloading an update, it happens from time to time. Can you retry and tell me if you still get the error?

**Comment by Nico207** [comment]
I've almost got the same error in Windows :
```
Updating to “pigments@0.17.1” failed.

TypeError: Cannot read property 'latest' of undefined
    at C:\Users\xxxxxxxxx\AppData\Local\atom\app-1.0.19\resources\app\apm\lib\install.js:285:28
    at Request._callback (C:\Users\xxxxxxxxx\AppData\Local\atom\app-1.0.19\resources\app\apm\lib\request.js:59:22)
    at Request.self.callback (C:\Users\xxxxxxxxx\AppData\Local\atom\app-1.0.19\resources\app\apm\node_modules\npm\node_modules\request\request.js:198:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (C:\Users\xxxxxxxxx\AppData\Local\atom\app-1.0.19\resources\app\apm\node_modules\npm\node_modules\request\request.js:1057:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (C:\Users\xxxxxxxxx\AppData\Local\atom\app-1.0.19\resources\app\apm\node_modules\npm\node_modules\request\request.js:1003:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16
    at process._tickCallback (node.js:448:13)
```

But you're rigth, it's just a network issue. I've tried some minutes after (I restart Atom to be sure) and all works fine.

**Comment by pgnd** [comment]
> Can you retry and tell me if you still get the error?

It took waiting overnight, but -- yep, problem gone.
