### ISSUE TITLE
Folding with dot markers

### ISSUE THREAD

**Issue by nunocastromartins** [abe33/atom-pigments#104]
The dot marker (both circle and square) is semi-visible when a rule is folded:

![expanded](https://cloud.githubusercontent.com/assets/8314616/10707095/9fc67696-79e5-11e5-92d0-77278fd257fc.png)
![folded](https://cloud.githubusercontent.com/assets/8314616/10707096/9fe78296-79e5-11e5-8af9-f8eb2fa82306.png)

I suspect that the marker should be hidden.

**Comment by abe33** [comment]
Hi @nunocastromartins, sorry for the late reply, I've got the patch ready, I'm trying to fix another issue and will release both at the same time, stay tuned!
