### ISSUE TITLE
Question: is there anyway to highlight custom colour mixins?

### ISSUE THREAD

**Issue by joshprice** [abe33/atom-pigments#105]
I have a custom `colour('colour-name', scale)` mixin which I'd like to evaluate and highlight.

Is there any way to achieve this?

**Comment by abe33** [comment]
Unfortunately, there's no simple solution actually, except by modifying the Pigments sources. Initially I wanted to expose a service to extend its behaviour, but as the current implementation is performing most of the color parsing in another thread there was issues to expose such service (workers doesn't have access to Atom services). I plan to refactor the parsing workers to allow this kind of extensions, but it's a huge task and I still haven't found the time to start it.

**Comment by abe33** [comment]
@joshprice A bit of update, I've finally found the time to refactor Pigments to allow extension, it's still in an early stage, and not published yet, but if you download master you'll be able to play with it.

**Comment by joshprice** [comment]
Awesome will check it out!

**Comment by abe33** [comment]
Just starting to write documentation about that: 

https://github.com/abe33/atom-pigments/blob/master/docs/extending-pigments.md

It still need to be improved with some example of how to use without a package (from the init script for instance).

**Comment by abe33** [comment]
Ok, the services are now available in latest release. I'm closing the issue then.

**Comment by joshprice** [comment]
Thanks!
