### ISSUE TITLE
Feature request: scale dot markers to text/font size

### ISSUE THREAD

**Issue by olmokramer** [abe33/atom-pigments#11]
The dot color markers have a fixed width/height of 16px/16px. That's fine with the defaults for font-size, but I like to zoom in/out sometimes, after which the markers are too large or too small:
![pigments dot overlap](https://cloud.githubusercontent.com/assets/3612514/7655553/7755ad84-fb24-11e4-808c-29c9c63a0daf.png)
Note how the markers are overlapping each other.

I suggest setting their width and height to
```coffee
Math.floor(atom.config.get('editor.lineHeight') * atom.config.get('editor.fontsize')) + 'px'
```
that way the markers always exactly fill 1 line vertically.

**Comment by abe33** [comment]
Thanks for the report, I agree it should be bound to the editor's styles, I'll make the change soon.

**Comment by olmokramer** [comment]
Awesome! Thanks :)

**Comment by abe33** [comment]
There's probably a need for some adjustments as I can't really rely on `vertical-align` to position the markers vertically. Let me know if you encounter a situation where the current rule gives unexpected results.

**Comment by olmokramer** [comment]
It looks great right now! But that's mostly because I'm using the default `1.3` for the `editor.lineHeight` setting. Other values for `editor.lineHeight` look a bit weird because the dot isn't centered on the line.

`(atom.config.get('editor.lineHeight') - 1) / 2` for the `margin-top` of the dots looks great in general. So you can solve this by `atom.observe('editor.lineHeight', ...)` and update the margin on the markers.
