### ISSUE TITLE
Referring to Azure (as in, Microsoft Azure) highlights with color

### ISSUE THREAD

**Issue by kendaleiv** [abe33/atom-pigments#110]
When referring to Azure, as in, [Microsoft Azure](https://azure.microsoft.com/) in the Atom editor, rather than the color, Azure is highlighted as the color.

I'll refrain from suggesting how to change this, or if it *should* actually be changed -- just making a note of something I've seen.

**Comment by abe33** [comment]
Hi @kendaleiv, yes, azure is a color defined in the SVG color palette, so, by default, Pigments will highlight it. You can prevent that behaviour by ignoring the context in which it appears using the [Ignored Scope](https://github.com/abe33/atom-pigments#ignored-scopes) setting. Let me know if you need more details on how to achieve it.

**Comment by kendaleiv** [comment]
Thanks for the info!
