### ISSUE TITLE
Disable color word highlight in the comments

### ISSUE THREAD

**Issue by denis-sokolov** [abe33/atom-pigments#112]
In my style files I often use words in comments.
The following looks disrupting:
<img width="444" alt="1" src="https://cloud.githubusercontent.com/assets/113721/11072824/73df796a-87f0-11e5-8432-51872a605074.png">

I can see the value of highlighting a complicated value in a comment, but simple color words are not worthy highlighting in the comments. Can I request an improvement to disable that?

If no, a simple option to blacklist colors would suffice. I will blacklist all simple words, even if that blacklists them from anywhere. Not that much value in highlighting ‘blue’ anyway.

Thank you!

**Comment by abe33** [comment]
Hi @denis-sokolov, have you take a look at the README? 
Specifically, these sections should cover your needs: 
- [Defining Where Pigments Applies](https://github.com/abe33/atom-pigments#defining-where-pigments-applies)
- [Ignored Scopes](https://github.com/abe33/atom-pigments#ignored-scopes)

**Comment by denis-sokolov** [comment]
My sincere apologies, I missed the ‘Ignored Scopes’ setting at first. Perhaps it is too fancily named for a quick scan. Again, sorry, and thank you.

**Comment by abe33** [comment]
No problem, it's a recurrent issue, and despite the fact I've tried to improve the documentation it seems it's still not as clear as it should be.
