### ISSUE TITLE
HSL with float values are being ignored

### ISSUE THREAD

**Issue by robsonsobral** [abe33/atom-pigments#115]
Hi!

Colors like `hsl(24.3, 100.0%, 82.5%);` aren't generating markers.

```sass
$x_light_orange   : tint(hsl(24.3, 100.0%, 82.5%), 35%);// no marker
$light_orange     : hsl(24.3, 100.0%, 82.5%);// no marker
$base_orange      : rgb(255,71,0);// marker
$dark_orange      : shade(rgb(255,71,0), 35%);// marker
$x_dark_orange    : shade(rgb(255,71,0), 50%);// marker
```

On previous sample, the first and the second just

- Pigments 0.18.1
- Atom 1.2.0
- Windows 10

**Comment by abe33** [comment]
I think you're the first person I see that uses float in hsv/hsl construct. I assumed hsl/hsv was using integers and not floats, but it seems I was wrong. I'll fix that soon.

**Comment by robsonsobral** [comment]
Sometimes, I convert a color to HSL and slowly edit the L channel. It's something I started to do before to adopt SASS.

Thank you, @abe33 !
