### ISSUE TITLE
Color words are highlighted

### ISSUE THREAD

**Issue by bobrocke** [abe33/atom-pigments#12]
Word in .md text such as `gold` are being highlighted as a color. The .gfm scope is not shown as an autocomplete scope.

**Comment by abe33** [comment]
Have you tried putting `\.source\.gfm` in the `Ignored Scopes` setting? 
It's purpose is to allow to hide markers using the grammar scope they belong to.

**Comment by bobrocke** [comment]
That was the adjustment needed! I thought the Autocomplete Scopes were the only ones to be parsed.

Thanks!

**Comment by abe33** [comment]
Autocomplete scopes allow to specify for which grammar the autocomplete provider kicks in. I thought the setting's descriptions was enough, I'll try to improve them :).
