### ISSUE TITLE
Ignored scopes not applied if marker type set to "gutter"

### ISSUE THREAD

**Issue by danbohea** [abe33/atom-pigments#127]
I've entered `\.comment` in the "Ignored scopes" to stop colour words in comments from being highlighted. This works fine with the exception of when "Marker type" is set to `gutter`.

**Comment by abe33** [comment]
Hi @danbohea. Nice catch, I'll try to take some time to fix that during this week.

**Comment by danbohea** [comment]
Many thanks. Fantastic package btw :)
