### ISSUE TITLE
Pigments blowing up console in Atom

### ISSUE THREAD

**Issue by fignoni** [abe33/atom-pigments#128]
Pigments is completely blowing up my console in Atom.  It means I can't work on any of my projects, and I can't use any of Atom's preferences or settings panes, which means I can't uninstall it using the GUI or run any updates.

The errors are uncaught (in promise) type errors coming from color-buffer-element.coffee.

pigments/lib/color-buffer-element.coffee:259 Uncaught (in promise) TypeError: this.editor.displayBuffer.getVisibleRowRange is not a function(…)

color-buffer-element.coffee:137 Uncaught TypeError: this.editor.displayBuffer.getVisibleRowRange is not a function

color-buffer-element.coffee:138 Uncaught TypeError: this.editor.displayBuffer.getVisibleRowRange is not a function

It also breaks a bunch of my other packages.  Basically Atom is unusable right now.

**Comment by fignoni** [comment]
Hey, I found this thread and my issue might be a duplicate of it: https://github.com/abe33/atom-pigments/issues/92

I will see if the solution in the threat fixes my issue.

**Comment by abe33** [comment]
You probably aren't using the latest pigments version, you should update it using `apm update` or through the settings view.

**Comment by fignoni** [comment]
No, I'm pretty sure I wasn't.  However, it broke the Atom GUI so that I couldn't get to settings at all.

I ended up using `apm uninstall` just to get rid of the issue, and I'll try reinstalling it with the most updated version, but for people who don't know how to do that via command line, having the GUI broken is bad.

**Comment by abe33** [comment]
Sure, but there's nothing I can do. I can't put a upper limit to a package compatibility range as I don't know when the core team will break some API. In that case I submitted the patch even before the official release of the new API, but if people don't update on time I can't do anything about it.

BTW, you can update from the CLI using `apm update`.
