### ISSUE TITLE
Display variables of @import files

### ISSUE THREAD

**Issue by enuzzo** [abe33/atom-pigments#130]
I use a main.scss file for general styling and a _colors.scss that I "@import".
I didn't find a way to show pigments colors on the side of my variables in the main.scss file.

**Comment by abe33** [comment]
Weird, it should works out of the box (that's one of the basic use case of the package). Is your `_color`.scss` file part of the project as well ? (Actually pigments doesn't really follow imports, but it rather consider every variables defined in a file of the project available project-wide)

**Comment by enuzzo** [comment]
I had to create a project in order to see them. It works now. Thanks.
