### ISSUE TITLE
Colors not lining up on update to 0.20.0

### ISSUE THREAD

**Issue by cherealnice** [abe33/atom-pigments#131]
![screen shot 2016-01-20 at 10 05 33 am](https://cloud.githubusercontent.com/assets/8879389/12452630/6b109fc2-bf5d-11e5-8311-615a58dcd0a8.png)

Using One Dark UI and Slatechalk syntax theme

**Comment by abe33** [comment]
Hi @cherealnice, I guess the markers came back to their rightful place after starting scrolling? I also see it from time to tim but I still haven't found a proper way to detect that situation.
