### ISSUE TITLE
Exclude specific css file/any file.

### ISSUE THREAD

**Issue by AngelsDustz** [abe33/atom-pigments#132]
Could you make it possible to make a costume exclude list?
So can you exclude ex: bootstrap.min.css because opening a file that big with pigments causes major lags. But since it's a minimalized file you don't really want it anyway.
So it would be really neat if you could make an exclude rule like *.min.css and it wouldn't run on any .min.css file or any other pattern you give up.

**Comment by abe33** [comment]
Hi @AngelsDustz, thanks for the suggestion, it doesn't look too hard to implement so I think I can give it a try.

**Comment by abe33** [comment]
It's now available as the `ignoredBufferNames` settings in v0.21.0

**Comment by JohJohan** [comment]
Very nice update, now we are able to load big file very fast just setting

*.min.css

Thank you

**Comment by AngelsDustz** [comment]
Cheers for the update works perfectly! (y)

**Comment by abe33** [comment]
Glad to know you find it helpful, it was easier than I thought and I really wonder why I didn't took this approach at first, my past me must have been really tired XD.
