### ISSUE TITLE
After Update Bug

### ISSUE THREAD

**Issue by roganoalien** [abe33/atom-pigments#138]
After the last update the packages has a bug the colors changes lines and starts doing weird things. The line were the colour is changes, f.e (line 52: color: #1c1c1c but appears at line 90, just de color hex value above other css).

**Comment by abe33** [comment]
Is it coming back to the right place after a small scrolling motion? It may happen that the measurement on restart are a bit off since the colors markers are serialized but will be created before the text editor is fully initialized
