### ISSUE TITLE
feature request - Show hex code in autocomplete

### ISSUE THREAD

**Issue by nickfmc** [abe33/atom-pigments#140]
It would be awesome if when pigments finds a scss variable for a color that in the autocomplete it showed the value as well as the swatch.

**Comment by abe33** [comment]
Hi @nickfmc, great suggestion, it's true that sometimes some nuances can be so close that you can't really differenciate them without knowing the color code.

**Comment by abe33** [comment]
The PR by @dzhiriki is now available in v0.24. 
You'll have to enable the `Extend Autocomplete To Color Value` setting. 

And then: 

![hexa in autocomplete](https://cloud.githubusercontent.com/assets/247140/13051161/fb46241e-d3f7-11e5-9de2-1787d7c99b12.png)

:sparkles: :sparkles: :sparkles: :sparkles:

**Comment by nickfmc** [comment]
Awesome work @abe33 so nice when designers have 8 shades of blue not having to go into my variables file every time to lookup the hex code. Thanks for such a fast feature add!
