### ISSUE TITLE
hey 

### ISSUE THREAD

**Issue by praneeshpradeep** [abe33/atom-pigments#143]
it is not downloading

**Comment by abe33** [comment]
Sorry, but can you me more details about the issue you encounter?

**Comment by praneeshpradeep** [comment]
Thank you for replying i had an issue that when i download pigments it wont
download ! just taking long tym and keep on failing and and i kept on
trying and succeeded installing but the atom keeps freezing after the
install of pigments ! i am using macbook pro 16 gig

**Comment by praneeshpradeep** [comment]
thanks for the reply i solved it
