### ISSUE TITLE
Stylus not coloring variables, not coloring after functions, not showing colors in autocomplete

### ISSUE THREAD

**Issue by nfdevil** [abe33/atom-pigments#144]
The plugin is showing the color on the hex-codes in my .styl file, but not on the variables that are equal to that hex-code, not when using lightness(variable,20%) and not in the autocomplete.

Atom version: 1.5.3
Plugin version: 0.24, but also didn't work on 0.23
OS: Windows 8.1 and Windows 10

![ss](https://cloud.githubusercontent.com/assets/7434048/13072013/562182da-d497-11e5-8742-e8ea8dbd66fb.png)

**Comment by abe33** [comment]
Hi @nfdevil, are you able to see your colors in the pigments palette? Also, could you share with me the output of the `Pigments: Report` command?

**Comment by nfdevil** [comment]
Hi @abe33, thanks for the fast reaction.

There are indeed no colors in my Palette.

When I do 'find colors' I get the following result: (style.css is the compiled version of the style.styl)
![findresults](https://cloud.githubusercontent.com/assets/7434048/13076619/bb899240-d4b3-11e5-8dea-200327e2134d.PNG)

**Pigments: report**
`{
  "atom": "1.5.3",
  "pigments": "0.24.0",
  "platform": "win32",
  "config": {
    "extendAutocompleteToColorValue": true,
    "extendAutocompleteToVariables": true,
    "traverseIntoSymlinkDirectories": false,
    "sourceNames": [
      "**/*.styl",
      "**/*.stylus",
      "**/*.less",
      "**/*.sass",
      "**/*.scss"
    ],
    "ignoredNames": [
      "vendor/*",
      "node_modules/*",
      "spec/*",
      "test/*"
    ],
    "ignoredBufferNames": [],
    "extendedSearchNames": [
      "**/*.css"
    ],
    "supportedFiletypes": [
      "*"
    ],
    "ignoredScopes": [],
    "autocompleteScopes": [
      ".source.css",
      ".source.css.less",
      ".source.sass",
      ".source.css.scss",
      ".source.stylus"
    ],
    "markerType": "background",
    "sortPaletteColors": "none",
    "groupPaletteColors": "none",
    "mergeColorDuplicates": false,
    "delayBeforeScan": 500,
    "ignoreVcsIgnoredPaths": true
  },
  "project": {
    "config": {},
    "paths": [
      "H:\\HtmlProjecten\\SPContracten\\style.styl"
    ],
    "variables": {
      "colors": 0,
      "total": 5
    }
  }
}`

**Comment by abe33** [comment]
Hmm, I'm a bit at loss here, do you think you can send me the stylus file to see if I can reproduce this locally? It does find 5 variables, but it either fails to parse them as color, or something is preventing pigments to go past the 5 first variables in the file

**Comment by nfdevil** [comment]
Here is the .styl-file. Just change the extension to .styl, Github doesn't support .styl uploading.
[style.txt](https://github.com/abe33/atom-pigments/files/132545/style.txt)

**Comment by nfdevil** [comment]
I've also did another test:

![stylus](https://cloud.githubusercontent.com/assets/7434048/13077622/3617d00c-d4ba-11e5-9d0a-44a8d129d886.PNG)

So it has problems with the variables I guess, not with the functions.

**Comment by abe33** [comment]
Ok, I've spotted the problem, it appears I fail to handle CRLF properly. I'll patch that asap.

**Comment by elkebirmed** [comment]
@abe33 : This works for an assignment operators but not with colon 

![screenshot from 2016-08-26 09-13-48](https://cloud.githubusercontent.com/assets/3056412/17998724/c1e4b18c-6b6d-11e6-8425-86f6d6381c9f.png)
