### ISSUE TITLE
Failed to update to 0.24.1

### ISSUE THREAD

**Issue by fionalu17** [abe33/atom-pigments#146]
Hi,

I'm unable to update Pigments today and here's the failed input:

EPERM, unlink 'C:\Users\fiona\.atom\packages\pigments\lib\tasks\load-paths-handler.coffee'

Hope this will help.

**Comment by abe33** [comment]
Hi @fionalu17, how are you updating Pigments? Through the settings view or through the command line? 
Also, it's weird that the path to your `.atom` directory appears as `fiona.atom` without a backslash between `fiona` and `.atom`. It looks like some path was badly generated. Maybe you can try to uninstall/reinstall Pigments to make sure the problem didn't come from a failure in the previous installation.

**Comment by fionalu17** [comment]
Hi @abe33 , I was updating Pigments through settings. Today I tried uninstall and reinstall and it worked! No more error messages, thanks for helping out :)
