### ISSUE TITLE
Rendering Problem

### ISSUE THREAD

**Issue by PinkiePieStyle** [abe33/atom-pigments#150]
Version 0.24.2
Long Line in CSS with inline Image
![pigments](https://cloud.githubusercontent.com/assets/7350146/13393896/a0d8e438-dee4-11e5-9b87-53887d8647dc.png)

**Comment by C-Bouthoorn** [comment]
Is this still occurring in the latest version?

**Comment by C-Bouthoorn** [comment]
Closed due to inactivity.
