### ISSUE TITLE
Invalid contribution link

### ISSUE THREAD

**Issue by PavelVanecek** [abe33/atom-pigments#152]
The contribution document of this repo (https://github.com/abe33/atom-pigments/blob/master/CONTRIBUTING.md) links to Atom contribution guidelines (https://atom.io/docs/latest/contributing) which no longer exists.

I found another Atom contribution guidelines on URL https://github.com/atom/atom/blob/master/CONTRIBUTING.md. Is it the correct document?

**Comment by abe33** [comment]
Hi @PavelVanecek, yes that's the one, the issue was reported on the Minimap but I forgot to update the other packages, thanks for reminding me of that.
