### ISSUE TITLE
Autocomplete not working in .sass files

### ISSUE THREAD

**Issue by esiao** [abe33/atom-pigments#154]
Hello autocomplete feature of the plugin doesn't seem to work for me only in .sass files.
If I change the file type to CSS, Less, SCSS, PostCSS the autocomplete shows up. If I'm in a Sass one it don't.

The search color feature works, the palette feature works and the debug shows that everything is fine, it's just that the autocomplete don't show up in my .sass files.

Here's the report (the paths array is not empty but I can't share the details).
```
{
  "atom": "1.5.3",
  "pigments": "0.24.2",
  "platform": "darwin",
  "config": {
    "autocompleteScopes": [
      ".source.css",
      ".source.css.less",
      ".source.css.scss",
      ".source.css.sass"
    ],
    "markerType": "dot",
    "mergeColorDuplicates": true,
    "sourceNames": [
      "**/*.css",
      "**/*.less",
      "**/*.scss",
      "**/*.sass",
      "**/*.styl",
      "**/*.stylus"
    ],
    "traverseIntoSymlinkDirectories": false,
    "ignoredNames": [
      "vendor/*",
      "node_modules/*",
      "spec/*",
      "test/*"
    ],
    "ignoredBufferNames": [],
    "extendedSearchNames": [
      "**/*.css"
    ],
    "supportedFiletypes": [
      "*"
    ],
    "ignoredScopes": [],
    "extendAutocompleteToVariables": false,
    "extendAutocompleteToColorValue": false,
    "sortPaletteColors": "none",
    "groupPaletteColors": "none",
    "delayBeforeScan": 500,
    "ignoreVcsIgnoredPaths": true
  },
  "project": {
    "config": {},
    "paths": [],
    "variables": {
      "colors": 10,
      "total": 28
    }
  }
}
```

At first I supposed a misconfiguration but sass is present in the sources, so if you have any idea of what's going on I'll be happy to have some help as Pigments is much ancred in my workflow now.

**Comment by abe33** [comment]
It looks like your `autocompleteScopes` setting holds a wrong value. The scope for sass is `.source.sass` and not `.source.css.sass`, leaving the default value should solve your issue.

![sass-completion](https://cloud.githubusercontent.com/assets/247140/13456615/53f272ca-e064-11e5-9222-4842bb8c4b1a.gif)

**Comment by esiao** [comment]
Hi abe33 thanks this was the issue, I had to relaunch Atom and reload Pigments to have it work again.

**Comment by gitachyut** [comment]
Hello esiao would you please help me configuring the atom for that sass issue cause I am also having the same issue that you had
