### ISSUE TITLE
Improve Package Loading Time

### ISSUE THREAD

**Issue by tillkruss** [abe33/atom-pigments#159]
Can you optimize the loading time for Pigments?

![screen shot 2016-03-12 at 12 25 00 pm](https://cloud.githubusercontent.com/assets/665029/13725121/845f6da0-e84d-11e5-86a4-b713c031646e.png)

**Comment by abe33** [comment]
I'll see what I can do, but I fear there's not much I can do as long as deserializers and views must be registered on package's loading, as most of the loading cost must come from that: https://github.com/abe33/atom-pigments/blob/master/lib/pigments.coffee#L277-L299

**Comment by C-Bouthoorn** [comment]
Closing in favour of the [master post](https://github.com/abe33/atom-pigments/issues/351).
