### ISSUE TITLE
Color Picker Integration

### ISSUE THREAD

**Issue by Mayccoll** [abe33/atom-pigments#16]
It would be very useful to integrate this plugin with a color picker. Clicking on the dot or an icon next to.

![picker](https://cloud.githubusercontent.com/assets/2009698/7692590/653ff384-fd8b-11e4-94a9-e71d95b5cf03.png)

Tnks

**Comment by abe33** [comment]
I was considering adding a color picker to pigments, I was waiting to see if the maintainer of the color-picker package was willing to update its package to support the 1.0 API.
I'm not sure when I'll be able to look at that, I have still a lot of work with performances and heavy project handing. But I'll definitely do something around that some day.

**Comment by ncammarata** [comment]
has there been any update on this?

**Comment by 6** [comment]
:+1: this would be awesome

**Comment by ghostlamma** [comment]
Can you guys add new change color check for this 2 plugins? it will be great if while i change color in color picker that would changed in color preview instantly, please if here somewho can... also me too maked something for that plugins, new gutter circle preview color, source code down below, just paste it in your atom stylesheet(File\Stylesheet...)
`atom-text-editor .gutter {
  order: 2;
}

atom-text-editor .line-numbers {
  order: 1;
}

atom-text-editor div .gutter-container div .gutter .custom-decorations div span {
  border-radius: 50%;
}

.ColorPicker-arrow:before {
  transform: translate(-80%, 0);
}

.ColorPicker-arrow:after {
  transform: translate(-80%, 0);
}

.is--flipped .ColorPicker-arrow:after {
    transform: translate(-80%, 0);
}

.is--flipped .ColorPicker-arrow:before {
    transform: translate(-80%, 0);
}`
