### ISSUE TITLE
First color name inside html element not highlighted

### ISSUE THREAD

**Issue by ricardograca** [abe33/atom-pigments#162]
With this:

    <div>Blue White</div>

The `Blue` will not be highlighted. Actually, you don't even need the full tags since this will produce the same result:

    >Blue White<

I'm not even particularly fond of color names being highlighted like that to begin with, but if it's there it should at least be consistent :)

**Comment by ricardograca** [comment]
That was fast :) Thanks :+1:

**Comment by abe33** [comment]
Note that in the latest version, by default, the color names should no longer highlighted in HTML file, the default is now to highlight them only in CSS and CSS pre-processor files. But you can still come back to the previous behaviour by adding `*` in the `Extended Filetype For Color Words` setting.
