### ISSUE TITLE
Font-family mistake

### ISSUE THREAD

**Issue by in-in** [abe33/atom-pigments#164]
Image will explain better than I
![crimson](https://cloud.githubusercontent.com/assets/8797432/14027948/3a3ccb1a-f20b-11e5-9a9c-39db5f459dce.png)

atom: 1.6.0
pigments: 0.26.0

**Comment by albtdd** [comment]
atom 1.6.2
pigments 0.26.0

![bug](https://cloud.githubusercontent.com/assets/12040245/14920422/c68e09c4-0e2d-11e6-9395-fb7485f477ba.jpg)

**Comment by abe33** [comment]
Actually pigments is not really able to tell whether a color name in a css file is in legit place or not as it's not a proper CSS parser. But you can still [manually set an ignore rule to prevent that from happening](https://github.com/abe33/atom-pigments#defining-where-pigments-applies).
