### ISSUE TITLE
Bourbon Shade/Tint getting Inverted

### ISSUE THREAD

**Issue by L337LUKE** [abe33/atom-pigments#166]
When using bourbons tint/shade which just mixes in bits of black(tint) and white(shade) pigments assigns the wrong colour value to the line.

The correct way should be in reverse to what it is now.  I've attached a screenshot in my atom editor and also a SassMeister Gist for you to look at the compiled.

Image in atom
![inverted_tint_shade](https://cloud.githubusercontent.com/assets/4473269/14116710/0d0c2cd6-f5d9-11e5-969c-a843275a982e.png)

SassMeister gist [SassMeister](http://www.sassmeister.com/gist/38eeafdddc1b22c57151d7d0115efa62)

**Comment by abe33** [comment]
Hi @L337LUKE, thanks for the report, I'll have to take a good look at that, because `tint` and `shade` have different implementations across all the pre-processors, and even maybe between bourbon and compass.

**Comment by L337LUKE** [comment]
I thought it might be that!

Also found out that if you call one of the variables somewhere inside atom the correct colour appears not the inverted colours when creating those shades/tints, bit of a weird one!

**Comment by GitLiamuk** [comment]
Would also love an update for this issue!

I was forever confused as to what was happening, I was either misunderstand bourbon (I'm new to bourbon) or pigments was bugged.

Can't wait to see this one fixed, my team hates this bug.

**Comment by abe33** [comment]
Hi @GitLiamuk, yeah I can understand how annoying it might be, I'm not really sure how nicely I can work around this issue though. Unless some kind of specific config I don't see how I can detect which sass lib is used, as tint and shade aren't part of sass core functions. It'll probably require a some new kind of conditions to enable/disable an expression at the parser level. I'll try to think of something.

**Comment by C-Bouthoorn** [comment]
A possible implementation could check for `@import` containing `bourbon` or `compass`?

**Comment by mattaningram** [comment]
Why not just have it be a manual setting in the package settings? Have a default, and if people want to change the behavior they can just toggle it in settings. No need for auto-detect or anything like that.

**Comment by abe33** [comment]
Yeah, I think the manual setting is much more convenient, I think it'll even be a project setting (accessible through the `Pigments: Project Settings` command) so that you don't need to change it whenever you change project

**Comment by abe33** [comment]
BTW, @C-Bouthoorn, I added you as a collaborator so that you can label and manage issues (or write patches if you feel like it).

**Comment by abe33** [comment]
This can now be changed at the package level using the `Sass Shade And Tint Implementation` setting and overridden in the pigment's project settings

**Comment by GitLiamuk** [comment]
@abe33 Thanks for this update, It's one of those updates that has gone completely unnoticed because everything is working exactly as intended. My OCD is no longer killing me while working with Bourbon now haha!

**Comment by L337LUKE** [comment]
@abe33 Awesome, Cheers for this dude! And likewise my OCD can be fixed! 👍  💯
