### ISSUE TITLE
Displays color on ID tag in CSS

### ISSUE THREAD

**Issue by yashghelani** [abe33/atom-pigments#167]
My ID tag in CSS is not a color but is still getting highlighted.
![screen shot 2016-03-30 at 12 57 53 am](https://cloud.githubusercontent.com/assets/17964039/14120894/87e822f0-f612-11e5-95cb-3e74b3f68b41.png)

**Comment by abe33** [comment]
Hi @yashghelani, nice catch, I'll push a patch for that soon.

**Comment by yashghelani** [comment]
Thanks @abe33

**Comment by michalbe** [comment]
I arrived here to file the same issue, :+1:

**Comment by yashghelani** [comment]
still not fixed though :/

**Comment by abe33** [comment]
Sorry for the delay, I completely forgot that issue.

**Comment by yashghelani** [comment]
the issue still isn't fixed
![screen shot 2016-07-19 at 4 07 26 pm](https://cloud.githubusercontent.com/assets/17964039/16947140/e4db491e-4dca-11e6-9871-7a15b3e7ba7b.png)

**Comment by andrewmccullough** [comment]
Still a problem! Any plans for a fix?
