### ISSUE TITLE
Copy to clipboard option

### ISSUE THREAD

**Issue by SASDOE** [abe33/atom-pigments#170]
Feature request: 

Under the contextual menu for Pigments, adding the ability to copy value to clipboard in the same fashion as Convert works.

**Comment by abe33** [comment]
Hi @SASDOE, thanks for the suggestion, it make sense to allow to copy the color value. 
I guess you would also expect to have the choice of the format when copying the value?

**Comment by SASDOE** [comment]
Amazing. Sorry I forgot to answer. 

Many thanks.

**Comment by abe33** [comment]
It's not released yet, but it'll be by the end of the week.
