### ISSUE TITLE
LaTeX support

### ISSUE THREAD

**Issue by pbregener** [abe33/atom-pigments#174]
It would be awesome to have LaTeX support.

The basic syntax is pretty straightforward:
```latex
\definecolor{orange}{RGB}{255,127,0}
\definecolor{orange2}{cmyk}{0,0.5,1,0}
\definecolor{orange3}{HTML}{FF7F00}

\textcolor{orange}{my orange text}
{\color{orange2} this is also orange}
```

https://en.wikibooks.org/wiki/LaTeX/Colors

The basic `color` package would be a great start, `xcolor` has a few more advanced options.

**Comment by abe33** [comment]
Sorry for the late reply, I'll be starting implementing this feature soon.
