### ISSUE TITLE
Freezing Atom

### ISSUE THREAD

**Issue by luizfox** [abe33/atom-pigments#175]
It seems like Pigments is locking the entire Atom application. 
It's a fresh installation of atom, and when I install the package, it locks the app in a few seconds.
If I close it and install through APM, when I open I get the same result.

My OS is Windows 10. 

Any ideas? Questions about data to debug?

Luiz.

**Comment by luizfox** [comment]
It looks like the problem is related with performance, specially when looking for various folder/files.
I disabled "Extended Search Names" and "Source name" options (changed to "none"), so I won't scan for my files. 
At least I'll have the color picker/visualizer function.

**Comment by abe33** [comment]
Hi @luizfox,

Can you provide me with a [timeline record](https://developers.google.com/web/tools/chrome-devtools/profile/evaluate-performance/timeline-tool?hl=en) and a [CPU profile](https://developers.google.com/web/tools/chrome-devtools/profile/rendering-tools/js-execution?hl=en) so that I can assert where the performance issue comes from?

**Comment by luizfox** [comment]
Yes, of course. Please take a look at
https://github.com/luizfox/random

**Comment by mcfarljw** [comment]
I can also report when installing pigments my ide freezes on `osx 10.11.4`. I have to manually remove it from the packages folder or load up atom in safe mode to get things running again. _It might be relevant to note that I'm opening atom from my `~/Desktop` directory._

**Comment by AlexSwensen** [comment]
I have the same issue. I should note that I'm opening a rather large project with a lot of .scss/sass files.

**Comment by UlfS** [comment]
Same here on linux.
Atom freezes seconds after opening a fairly large project - disabling pigments with `apm` "fixed" it.

**Comment by astucieuxzephyr** [comment]
Same here on Windows 10, with ATOM 1.8.0 and no other package installed. This is a very annoying bug.

**Comment by andrewmccullough** [comment]
Same, but I'm using OS 10.11. Please fix ASAP!

**Comment by fishcharlie** [comment]
Having the same issue where this plugin is freezing Atom on Mac OS

**Comment by tschleuss** [comment]
I discovered today too, i disable my plugins one by one to find what was freezing my client (mac).
When disabled pigments, atom stops freezing.

**Comment by mariohmol** [comment]
Same in mac.. i had to disable one by one.. when i open a big project.. it freezes..  if you want to test in a real project.. use a ionic demo projec.. https://github.com/zachsoft/Ionic-Material/archive/master.zip

I tested ignorin min files (*.min.*) ... it helps.. freezes but just for a few seconds.. 

One suggestion is to leave .min. files excluded as default

**Comment by MatrixV01** [comment]
Myself and a co-worker have the same issue of Atom freezing when pigments is enabled, but only when opening a project sub-folder. When I open a project from the root folder Atom doesn't freeze with pigments enabled.

**Comment by MatrixV01** [comment]
Same issue. Pigments freezes Atom on large projects.

**Comment by christopherjohns1** [comment]
I am also have the freezing issue. But my issue only occurs on minified JS & minified CSS files where there's a very long amount of characters on a single line.

**Comment by pzuraq** [comment]
Also having this issue on a particularly large project.

**Comment by refactorized** [comment]
I am seeing this issue only when opening a large, compiled, css file - the source files that generate it all seem to scan fine

**Comment by clabnet** [comment]
Same issue. I uninstalled pigments plugin. Now Atom run fine.

**Comment by medBouzid** [comment]
same issue for me, it's freezing atom and that cause freezing the whole system until I do a hard restart

**Comment by fishcharlie** [comment]
@abe33 This ever going to get fixed??

**Comment by C-Bouthoorn** [comment]
@fishcharlie It probably will, but it seems that Abe is focused on another project now. I suppose/hope that he'll come back here soon. In the meantime, I'm trying to fix small issues, but this seems like a big issue, which I'm not able to fix easily.

**Comment by C-Bouthoorn** [comment]
Closing in favour of the [master post](https://github.com/abe33/atom-pigments/issues/351).
