### ISSUE TITLE
Color Marker Overlapping Text

### ISSUE THREAD

**Issue by jdugdown** [abe33/atom-pigments#178]
Just updated to 0.26.3 and now the preview markers are overlapping the text. Tried reinstalling the package and restarting the editor but the problem persists.

When the marker type is set to background:
![pigments-background](https://cloud.githubusercontent.com/assets/2228271/15234008/1af7a8d8-1862-11e6-8fdf-142e3de1b06d.PNG)

When the marker type is set to dot:
![pigments-dot](https://cloud.githubusercontent.com/assets/2228271/15234009/1af7fb62-1862-11e6-8e00-c6e0beb5dafe.PNG)

The other types have similar issues.

**Comment by febLey** [comment]
Got the same issue. I'm using 1.8-beta3

**Comment by alexcris** [comment]
Same here.

![screen shot 2016-05-17 at 12 02 41 am](https://cloud.githubusercontent.com/assets/7550348/15311657/b5003e00-1bc2-11e6-802d-d62d6242f80e.png)

**Comment by abe33** [comment]
Hi there, yes, this is something that occurs more and more recently, I'm still not sure what triggers this (probably some race condition on a buffer update that leads the decorations to get wrong coordinates). Generally the decorations come back to their normal position once rerendered but yeah, it's a bit annoying that I can't find why it occurs.

Ideally I would like to get rid of my custom decorations to use native ones, but it's still not possible to get the same feature list so I guess we'll have to stick with that until I got some time to work on a PR for Atom to introduce some new decoration types.

**Comment by BurningLutz** [comment]
+1

**Comment by SentientSeven** [comment]
I'm pretty sure this is something that has been introduced with one of the latest patches; both v0.26.3 and v0.26.2 have this problem, when I roll back to v0.26.0 the problem is solved. Also this doesn't resolve when the page rerenders (at least not for me), regardless of theme selected.

**Comment by paralel-git** [comment]
Same here. I roll back to v0.26.0 like @SentientSeven did and it's ok now on v1.7.4.

**Comment by abe33** [comment]
Please check with v0.27.0, this should no longer be a problem for dot decorations. As for the problem of @jdugdown, using the new `native-background` decoration should help greatly. Let me know if it improved things for you.

**Comment by alexcris** [comment]
Fixed. Thanks @abe33 👍

**Comment by jdugdown** [comment]
The regular background, dot, square, etc. are all fixed for me as well. Thanks a ton @abe33 this is one of my favorite Atom packages.
