### ISSUE TITLE
color highlight float over Text

### ISSUE THREAD

**Issue by mehdi-alouane** [abe33/atom-pigments#180]
![screenshot from 2016-05-13 22 45 11](https://cloud.githubusercontent.com/assets/4208162/15262864/0b172cc6-195d-11e6-9d0e-b4d68bdc31c4.png)

**Comment by abe33** [comment]
@mehdi-alouane does the dots come back into place after scrolling back and force or editing the file or are they always in that disposition?

**Comment by mehdi-alouane** [comment]
they coming back in there place after scroling but if you scrol up and down they take that position [Soryy for my bad english :)]

**Comment by danieldogeanu** [comment]
I have this problem too. Though they float at the end of the lines. If I switch to background or other color mode, they stretch all the way to the beginning of the row.

![colors-over-code](https://cloud.githubusercontent.com/assets/5739197/15475883/e32c50dc-2114-11e6-9793-f447dd1193f7.PNG)

![colors-over-code-bg](https://cloud.githubusercontent.com/assets/5739197/15475882/e328813c-2114-11e6-8ba4-c3d890b305e9.PNG)

**Comment by llanginger** [comment]
Same problem here - scrolling away and back again puts them almost in the right place but they overlap the last few characters of the line.

**Comment by abe33** [comment]
You can now use the new native decoration in pigments v0.27.0.
