### ISSUE TITLE
Color detection in commented text

### ISSUE THREAD

**Issue by alearcy** [abe33/atom-pigments#184]
Hi! is it possible to remove words colors detection inside code comment? 

![schermata 2016-05-18 alle 14 47 43](https://cloud.githubusercontent.com/assets/5402295/15359007/8562d022-1d07-11e6-957f-f82dc92e3201.png)

**Comment by abe33** [comment]
Have you tried to set `\.comment` in the ignored scopes setting? 
👇 
https://github.com/abe33/atom-pigments#defining-where-pigments-applies

**Comment by alearcy** [comment]
Oh man! I saw it just now! thanks, it works. Thanks!
