### ISSUE TITLE
False Positives

### ISSUE THREAD

**Issue by jBot-42** [abe33/atom-pigments#186]
![screen shot 2016-04-09 at 7 50 04 pm](https://cloud.githubusercontent.com/assets/5308655/15451320/52d3d91e-1f71-11e6-9aeb-661525f61b51.png)
![screen shot 2016-04-09 at 7 52 32 pm](https://cloud.githubusercontent.com/assets/5308655/15451321/555557da-1f71-11e6-834d-1425cb3bced8.png)

I have been encountering an interesting issue with atom-pigments that is causing colors to be detected in lines of code where there are none. This appears to only happen when programming in C++. I am using the latest version of Atom on OS X 10.11.5.

**Comment by abe33** [comment]
Hi @jBot-42, that's really a weird issue, would you be kind enough to share a sample file with me so that I can try to reproduce that? Also, can you provide me with the output of the `Pigments: Report` command?

**Comment by jBot-42** [comment]
The issue seems to have stopped.
