### ISSUE TITLE
MarkerType:dot  

### ISSUE THREAD

**Issue by wagnlinzh** [abe33/atom-pigments#187]
MakerType:dot

![2](https://cloud.githubusercontent.com/assets/3985726/15453846/528d1dee-2057-11e6-857f-845c521fdebf.png)

![snipshot](https://cloud.githubusercontent.com/assets/3985726/15453838/209c3afe-2057-11e6-9eeb-851f7448e62e.png)

**Comment by GU5TAF** [comment]
Duplicate of #178

**Comment by abe33** [comment]
Yup, thanks @GU5TAF, closing in favor of the original.
