### ISSUE TITLE
dot, square-dot position

### ISSUE THREAD

**Issue by cortauri** [abe33/atom-pigments#191]
dot and square-dot marker types margin-left value ist to small, markers actually touching the code in Atom 1.7.4

**Comment by DanielPintilei** [comment]
Same here. Setting `margin-left` to 15-20px for `.dot` works for me.

**Comment by abe33** [comment]
Hi there, can you confirm whether you still get that issue with 0.27?

**Comment by abe33** [comment]
Also, it's a duplicate of #178

**Comment by DanielPintilei** [comment]
Looks better with 0.27 but it's not fixed, the dot covers the `;`. Changing `transform: translate(50%, -50%);` to `transform: translate(100%, -50%);` works for me.

**Comment by abe33** [comment]
@DanielPintilei And with the `native-dot` type instead?

**Comment by DanielPintilei** [comment]
Setting the marker to native dot gives me and error.
".../.atom/packages/pigments/lib/color-buffer-element.coffee:288"

**Comment by danny505d** [comment]
I was also getting this error (even after the upgrade to 0.27). I uninstalled and re-installed, and seemed to clear it up for me without changing anything else.

**Comment by defking** [comment]
Re-installing the plugin fixed the problem.

**Comment by DanielPintilei** [comment]
Looks good in 0.27.1

**Comment by SentientSeven** [comment]
0.27.1 fixed this for me, thanks @abe33 !
