### ISSUE TITLE
No Settings Page??

### ISSUE THREAD

**Issue by jordanbrauer** [abe33/atom-pigments#195]
Where did all of the settings go? Now it's just a readme that doesn't even tell you where to change the values for settings.... No common config file found in the pigments directory to do this either....?

**Comment by abe33** [comment]
Hi @jordanbrauer, can you tell me about your config, because as far as I can tell there's no issues on master.
![settings_ __users_cedric_development_ruby_leclerc-es-v2](https://cloud.githubusercontent.com/assets/247140/15702062/20a20748-27de-11e6-9112-563cf87fc668.png)

**Comment by jordanbrauer** [comment]
Here a screenshot of my settings page for your plugin (I have an update available for the plugin now, so I will update and see if that fixes my problem). Notice how the Settings area is missing and shows the Read Me? 
![image](https://cloud.githubusercontent.com/assets/18744334/15717621/6dae0140-27ed-11e6-97d6-b64e8d544f4d.png)

The Settings section is below the Read Me, but doesn't have checkboxes, and editable fields... They are just more of the readme.
![image](https://cloud.githubusercontent.com/assets/18744334/15717725/e1efda7e-27ed-11e6-9558-b8e99bcc7064.png)

Like I said, I will apply the update and see if that fixes it, but figured I would show you the issue before doing so

**Comment by jordanbrauer** [comment]
@abe33 The update worked. Here is a screen shot for comparison between the two. 
![image](https://cloud.githubusercontent.com/assets/18744334/15717999/02a08646-27ef-11e6-9107-5db134b2a61d.png)


Not sure if you are wanting to deal with this 'bug' or are just gunna sweep it under the rug since the update worked for me lol!
