### ISSUE TITLE
Weird text with "native-background"

### ISSUE THREAD

**Issue by daltones** [abe33/atom-pigments#196]
I've noticed that atom-pigments have become very slow (as #188). So today I tried switch to `native-background` markers. The background renders normally, but the text renders a weird string instead of the original color text, something like the coordinates of the background rectangle.

This is the CSS file:
```css
a {
  background-color: #C00;
  color: #00C;
}
```

And this is what appears:
![captura de tela de 2016-05-30 18-21-57](https://cloud.githubusercontent.com/assets/5603632/15658497/792c929e-2693-11e6-94a2-614ff12a6b0d.png)

Pigments 0.29.0
Atom 1.7.4 on Arch Linux

**Comment by abe33** [comment]
Hi @daltones, thanks for the report, this should be fixed in 0.29.1.

**Comment by daltones** [comment]
Thanks! :)
