### ISSUE TITLE
thinks @component-line-height is a color

### ISSUE THREAD

**Issue by braver** [abe33/atom-pigments#2]
In isotope's [buttons.less line 117](https://github.com/braver/isotope-ui/blob/master/styles/buttons.less#L117) it highlights `@component-line-height` in black:

![screen shot 2015-04-22 at 19 57 50](https://cloud.githubusercontent.com/assets/2543659/7281431/df0b17aa-e929-11e4-961d-7ccafc740571.png)

This variable is defined in `ui-variables.less` as a value in `rem`.

**Comment by abe33** [comment]
I just downloaded your theme so that I can test that as well as the performances issues you mentionned on discuss.

It shouldn't be hard to fix that so I think I'll publish a patch this evening.
