### ISSUE TITLE
Randomly stops working

### ISSUE THREAD

**Issue by devlemire** [abe33/atom-pigments#202]
It'll work sometimes and then randomly stop. Not sure why.

**Comment by C-Bouthoorn** [comment]
A stack strace or a file (structure) would speed up the fixing process

**Comment by michael-yx-wu** [comment]
Restarting atom generally solves this issue for me. I've gotten into states where the colors show up in autocomplete, but not on actual variables in the file.

**Comment by kleerkoat** [comment]
maybe this might help track it down....

if I go into `Pigments>Settings` and goto `Supported Filetypes` and delete the last filetype and type it back in it triggers Pigments.

**Comment by C-Bouthoorn** [comment]
Closing in favour of the [master post](https://github.com/abe33/atom-pigments/issues/351).
