### ISSUE TITLE
No working ATOM version 1.9.8

### ISSUE THREAD

**Issue by jousmo** [abe33/atom-pigments#214]
Crash ATOM

**Comment by C-Bouthoorn** [comment]
Do you have any more information? Stacktrace, apm version, pigments version, node version, OS, configuration file?

**Comment by lengziyu** [comment]
Me too, Atom version is v1.9.8, Windows 7 64 - bit error and then affect the search function can't run, unloading line, it's okay, this several days before...

**Comment by C-Bouthoorn** [comment]
I can't reproduce this issue in Atom and Atom-Beta on Ubuntu. I'm using all the default settings from pigments.

#### Simple versions
Ubuntu 16.04
Atom 1.9.8
Atom Beta 1.10.0-beta5
Pigments 0.31.2

#### Detailed versions
`$ uname -a`
`Linux 4.4.0-32-generic #51-Ubuntu SMP Tue Jul 19 18:09:07 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`
`$ node -v`
`v5.10.0`
`$ npm -v`
`3.8.3`
`$ atom -v`
`1.2.0-dev`
`$ atom-beta -v`
```
Atom    : 1.10.0-beta5
Electron: 0.37.8
Chrome  : 49.0.2623.75
Node    : 5.10.0
```
`$ apm -v`
```
apm  1.1.1
npm  2.13.3
node 0.10.40
python 2.7.12
git 2.9.2
```
