### ISSUE TITLE
Right click to change colour format

### ISSUE THREAD

**Issue by Aarilight** [abe33/atom-pigments#22]
Feature request. If you right click on a colour, it'd be cool if one of the options was to change the format of the colour, for instance from `rgb(0,0,0)` to `#000`. It'd be really handy for stuff that's much harder to calculate in your head, and nice to have to match colour formats in a document. Also, for instance, you could have something like `darken(#fff, 10%)` and you could right click to convert it to a hex value. How neat would that be? 
\</pipe-dreams>

**Comment by abe33** [comment]
Sounds interesting, I can't give an ETA, but I'll definitely think about that.

**Comment by v3ss0n** [comment]
:+1:  thats very useful , but i think it will take a bit of work to do.

**Comment by abe33** [comment]
Hi, a small update post, I plan to work on that feature this weekend, and it'll be actually much simpler to implement that I thought at first, so I think I'll even make that feature available using commands so that you can also trigger the change using the keyboard. 

Stay tuned

**Comment by v3ss0n** [comment]
@abe33 , You Rock!
