### ISSUE TITLE
Installing “pigments@0.33.1” failed.

### ISSUE THREAD

**Issue by MichielConradie** [abe33/atom-pigments#221]
I tried to install through atom and the apm installer but received the above mentioned error with the following output:

```
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Users\\430w47\\AppData\\Local\\atom\\app-1.9.9\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\430w47\\AppData\\Local\\atom\\app-1.9.9\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\430w47\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\430w47\\.atom\\.apmrc" "install" "C:\\Users\\430w47\\AppData\\Local\\Temp\\d-116726-11956-18zjmc5\\package.tgz" "--target=0.37.8" "--arch=ia32"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! file C:\Users\430w47\.atom\.apm\debug\0.7.4\package\package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Unexpected token '\u0000' at 1:1
npm ERR! 
npm ERR! ^
npm ERR! File: C:\Users\430w47\.atom\.apm\debug\0.7.4\package\package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR! 
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse
```

**Comment by C-Bouthoorn** [comment]
It looks like the package.json was corrupted during the download. Could you maybe try deleting that file/folder and re-installing?

**Comment by MichielConradie** [comment]
I deleted everything i found for pigments in the atom folder but i still got the same error message.

**Comment by MichielConradie** [comment]
i got the same meassage with 0.34.0 version
nstalling “pigments@0.34.0” failed.Hide output…

npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "C:\\Users\\430w47\\AppData\\Local\\atom\\app-1.9.9\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\430w47\\AppData\\Local\\atom\\app-1.9.9\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\430w47\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\430w47\\.atom\\.apmrc" "install" "C:\\Users\\430w47\\AppData\\Local\\Temp\\d-116729-10168-rs9u4x\\package.tgz" "--target=0.37.8" "--arch=ia32"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! file C:\Users\430w47\.atom\.apm\debug\0.7.4\package\package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Unexpected token '\u0000' at 1:1
npm ERR! 
npm ERR! ^
npm ERR! File: C:\Users\430w47\.atom\.apm\debug\0.7.4\package\package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR! 
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse

**Comment by C-Bouthoorn** [comment]
Did you remove the `.atom\.apm\debug\0.7.4\package\package.json` file?

**Comment by MichielConradie** [comment]
sorry no will try that also and let you know.
thnx

**Comment by MichielConradie** [comment]
I'm still getting the same error

**Comment by MichielConradie** [comment]
i had to uninstall atom.io and delete everything and reinstall atom after that it worked the install of the atom-pigments package

**Comment by C-Bouthoorn** [comment]
That's weird, but I'm happy it works for you now!
