### ISSUE TITLE
Feature request: support css variables / custom properties

### ISSUE THREAD

**Issue by macgyver** [abe33/atom-pigments#224]
[CSS variables/custom properties](https://www.w3.org/TR/css-variables/) have [support in current versions of all major browsers except IE/Edge](http://caniuse.com/#search=css%20variables) and can be used today e.g. with the help of [postcss-custom-properties](https://github.com/postcss/postcss-custom-properties)

This is how people will be writing css in the very near future, but it looks like this currently:
![screen shot 2016-09-04 at 2 28 54 pm](https://cloud.githubusercontent.com/assets/1163/18233432/e10f52ce-72ac-11e6-867f-5e3da1605a0d.png)

I propose the pigments package add support for it!

**Comment by abe33** [comment]
Isn't that already the case? Looks like my tests aren't as reliable as I thought

**Comment by abe33** [comment]
Ok, the issue was just that `*.css` wasn't part of the default config for variables sources.
