### ISSUE TITLE
Pigment doesn't work!

### ISSUE THREAD

**Issue by Aakash30Sethiya** [abe33/atom-pigments#225]
I don't know why pigment doesn't work in my atom....

I am using atom version "1.10.2".

**Comment by C-Bouthoorn** [comment]
OS version? Package list? Stacktrace? Some more information would be helpful :blush:

**Comment by CalebGrove** [comment]
I'm having the same problem. Here's my pigments-report: https://gist.github.com/CalebGrove/1ba47847853ba5dd87114785c39859a7

I'm using OS X El Capitan. I've tested with UI theme and syntax theme "One Dark". The palette and "find colors" works just fine — it's just that the color dots don't appear in Atom.

**Comment by CalebGrove** [comment]
Okay, this is odd. I removed my list of custom supported filetypes (`scss, css, html, php, less, sss`) and now Pigments is working swell in the scss file that I was working on.

However, reinstating my custom list doesn't break Pigments now.

Huh.

**Comment by C-Bouthoorn** [comment]
At least it works now, but I'm not sure what caused the problem.

**Comment by Aakash30Sethiya** [comment]
after updating plugin it work's well
