### ISSUE TITLE
Support RGBA floating type values.

### ISSUE THREAD

**Issue by bedm0203** [abe33/atom-pigments#226]
Parsing of QML files with rgba colors defined with Qt.rgba(0.0, 1.0, 0.0, 1.0) does not work. If I replace the floating type values with integer values, then syntax color highlighting works, but it's not what is expected by Qt. Parsing of rgba floating type values would be great.

**Comment by abe33** [comment]
Hi @bedm0203, what is the extension for QML files? `*.qml` ?

**Comment by bedm0203** [comment]
Yes, QML files' extension is *.qml. It is worth noting that we can also use the same function in C++.
