### ISSUE TITLE
最新版pigments，在win7上无法工作

### ISSUE THREAD

**Issue by lore520** [abe33/atom-pigments#228]
不知道是什么原因导致在win7上无法运行，会导致ATOM卡死，卸载后，ATOM正常！

**Comment by C-Bouthoorn** [comment]
It would be nice if you could translate this to English, so we understand what your problem is. 

Google Translate says:
`I do not know what causes can not run on win7, will lead ATOM stuck, after unloading, ATOM normal!`

**Comment by abe33** [comment]
Hi @ lore520，你能用英语交流吗？ 我缺少很多信息，开始帮助你。

It was made using google translate, I'm not sure it'll be understandable...

**Comment by scfkcf** [comment]
I just tried to translate what lore520 had said:

Title: The latest pigments can't work on win7
Content: I don't know why it can't work, the latest pigments will stuck Atom. However when I unstall pigments, everything become normal.

**Comment by C-Bouthoorn** [comment]
Seems to have been solved. Closing
