### ISSUE TITLE
0.35.0 crashes atom in large projects

### ISSUE THREAD

**Issue by Eldar-X** [abe33/atom-pigments#229]
When I use the pigments version 0.35.0, atom crashes and my cpu going crazy in large projects. The problem disappears when I downgrade to 0.34.0 version.

My system is macOs Sierra 10.12

**Comment by OctaneInteractive** [comment]
Yeah, I have the same freezing problem here.

I've had to launch via the Terminal on the Mac in safe mode.

I'm running OS X 10.11.6

**Comment by ccuilla** [comment]
Similar case for me. Hangs on one particular project but not others. No logging or stack trace that I can find.

macOs Sierra 10.12
Atom 1.10.2
pigments 0.35.0

**Comment by Eldar-X** [comment]
Also I see problem starts after reboot atom only not directly after update package

**Comment by abe33** [comment]
Hi there, is it possible for you to share a bit of information about the projects that cause that freezes/crashes ? It's always hard to guess what could go wrong without a real project. 

Also, I noticed that 0.35  was released with some remaining logs in a critical part of the plugin, so maybe it's just the Atom console that was flooded by message, try update to 0.35.1 to see if you get the same issue.

**Comment by OctaneInteractive** [comment]
I got an update notification for Pigments by Atom, applied the update, quit Atom and opened it again, and after that it freezes each time I start it, unless it's in safe mode.

When I check with Activity Monitor on the Mac, Atom and it's Helper are chewing up the CPU between them, and I have to force quit them.

**Comment by Eldar-X** [comment]
My project is node.js project with many modules. Yesterday when i try to make update 0.35.1 it freeze also but now i try again and don't see same problem not sure what was changed. I will follow this issue and if it will freeze again i will report here.

**Comment by abe33** [comment]
@Eldar-X node_modules should be ignored by default, so unless you change the `ignored names` setting it shouldn't scans in that directory. Also, whenever you make an update from within Atom the package's code isn't completely reloaded (only the main file is, which leads to numerous errors when some method signatures change between updates).

@OctaneInteractive Please make sure you're on 0.35.1 or higher to see if the issue still remain. I highly suspects it has to do with the remaining logs I mentioned above.

**Comment by Eldar-X** [comment]
I can't see any issues left. Thanks for fixing problems.
