### ISSUE TITLE
Getting a lot of logging from color-context

### ISSUE THREAD

**Issue by danielbrodin** [abe33/atom-pigments#230]
Hey,

I'm getting a lot of logging from `color-context.coffee` for some reason in the dev console. Was probably a couple of hundred logs showing, and over 35000 that was hidden automatically.

It's apparently from row 60, but couldn't find any `console.log` there so not sure why it happens.

**Comment by abe33** [comment]
Hi @danielbrodin, yeah it was my mistake when releasing 0.35, 0.35.1 was released soon after and no longer log anything. 

🙇 my deepest apologies for the annoyance.
