### ISSUE TITLE
"Pigments successfully reloaded" popup -- Can I turn this off?

### ISSUE THREAD

**Issue by dsifford** [abe33/atom-pigments#232]
Hi there,

Thanks for your work on this. I'm curious if I'm able to disable the popup message for pigments since it's pretty intrusive, doesn't go away automatically, and pops up every time I change projects using `project-plus`.

Would it perhaps be better to only display a pop-up message when something bad happens? In other words, stick to the "no news is good news" philosophy?

Another argument for this is: If I switch to a systems language project (C++ for example) I get this message:

![image](https://cloud.githubusercontent.com/assets/5240018/19059663/a935ca8a-89af-11e6-860c-8d8ba8b067ba.png)

Not super useful and sort of annoying.

Thanks for considering and thanks again so much for the package. Super handy! :smile:

**Comment by abe33** [comment]
I didn't know that switching projects in project-plus are triggering a Pigments reload, is that something you did setup yourself?

**Comment by abe33** [comment]
So in v0.37.0 You'll find a setting to activate/disable notifications on reload, or just make them automatically dismissed after a timeout.

**Comment by dsifford** [comment]
@abe33 Wow! Thanks so much. You work fast! 😄

**Comment by shanemgrey** [comment]
I imagine there are use cases for the notification of reloading.  And I have turned the setting off after reading this thread. But perhaps the more common case is for users who don't need to have the notification on by default?  

It doesn't dismiss on a timeout, and requires user action to remove it by default.

**Comment by Toub** [comment]
Thanks @abe33

I guess this should be off by default!
