### ISSUE TITLE
Latest update sops CSS autocomplete to stop working

### ISSUE THREAD

**Issue by ralphvandenberg** [abe33/atom-pigments#234]
Since latest update (0.37.0), it breaks the autocomplete packages. Disabling pigments addon and everything works fine again.

**Comment by abe33** [comment]
Hi @ralphvandenberg, would you be kind enough to provide me with a screencast of the issue? (a gif would be perfect). I'm not sure what do you mean by breaking the autocompletion. And on my config I didn't noticed any changes.

**Comment by C-Bouthoorn** [comment]
Not enough information, seems to have been fixed
