### ISSUE TITLE
Freezes Atom when opening large minified files

### ISSUE THREAD

**Issue by acondiff** [abe33/atom-pigments#235]
Please disable Pigments on all large files and minified files that are on a single line as it freezes atom and when it does render on single line files the color preview circle overlays the code.

**Comment by C-Bouthoorn** [comment]
Could you specify what a "large file" is? Because Pigments works fine for files with over 1000 lines.

**Comment by C-Bouthoorn** [comment]
Closing in favour of the [master post](https://github.com/abe33/atom-pigments/issues/351).
