### ISSUE TITLE
Duplicated colors in color palette

### ISSUE THREAD

**Issue by lefoy** [abe33/atom-pigments#245]
This might be related to issue #171 . My Sass variables are defined with dashes but I'm getting duplicates in my color palette (variables with underscores are created).

Is there a way to hide variables with underscores in my color palette?

Variables: https://i.gyazo.com/399feaaacaa2ffd288127dea3d45e122.png
Color Palette: https://i.gyazo.com/e0738e5aaa0b4b555ee0dee9874e1c62.png

Atom version: 1.11.2
Pigments version: 0.37.0

Thank you!

**Comment by abe33** [comment]
Hi @lefoy, actually sass allow the two forms altogether, so you can use both in your code (that's why I needed to create a duplicated entry for the alternate form). I already hide the alternate version in the autocomplete so I can completely do the same in the palette view.

**Comment by lefoy** [comment]
I would really like an option to hide it from the palette too :) We're working with a lot of colors and it's a bit confusing with all the duplicates. Thank you!

**Comment by C-Bouthoorn** [comment]
It looks like the referenced commit fixed this, so I think it can be closed.

**Comment by lefoy** [comment]
Can you release this fix please? I still have duplicates in Atom. I think this commit was made after the latest release of Pigments.

**Comment by mbryksin** [comment]
Hey! I guess the latest release still does not have option in UI to hide alternative forms?
Please give some advice, how can I manage it  🙏
