### ISSUE TITLE
Not working on linux

### ISSUE THREAD

**Issue by xahon** [abe33/atom-pigments#246]
It's not working on Linux. Before install it says "Version 0.37.0 is not the latest version available for this package, but it's the latest that is compatible with version of atom". But there is no another version for Linux

I've tried install via apm, but package not showing up in packages tab too

**Comment by C-Bouthoorn** [comment]
Try updating Atom? 1.12.1 is the latest stable, 1.13.0-beta1 is the latest beta. The beta version works for me, not sure about the stable one, but should work too.

**Comment by abe33** [comment]
Hi @xahon, it seems there're some issues with versions constraints on `apm`, please see #247, we'll try to keep the discussion in on place.
