### ISSUE TITLE
With 1.13 beta release, default .region styles are more specific than `.pigments-highlight-0 .region`

### ISSUE THREAD

**Issue by bjmiller** [abe33/atom-pigments#248]
Now that atom has removed use of the shadow DOM, styles that apply to .region elements are out in the open, and are superceding the pigments marker background color style.

Default atom selector: `atom-text-editor .highlight .region, atom-text-editor .highlight .region`
Pigments style selector: `.pigments-highlight-0 .region`

As a quick fix, you can `!important` the generated styles, and after that spend some time deciding on a more appropriate specificity.

**Comment by abe33** [comment]
Hi @bjmiller, which type of decoration are you using? I'm on 1.13 since it hitted master and didn't see much issues with native decorations.

**Comment by C-Bouthoorn** [comment]
Seems to have been fixed. Closing
