### ISSUE TITLE
Color not displayed

### ISSUE THREAD

**Issue by farazaulia** [abe33/atom-pigments#249]
Sir, pigments doesnt show colors on my atom.
Can u help me to fix this?

**Comment by reznord** [comment]
@farazaulia this bug is already reported at https://github.com/abe33/atom-pigments/issues/247.

**Comment by C-Bouthoorn** [comment]
Is this issue still persisting, or has it been solved?

**Comment by C-Bouthoorn** [comment]
This seems to have been solved. Closing
