### ISSUE TITLE
Pigments in Atom 

### ISSUE THREAD

**Issue by GrimmjowGR** [abe33/atom-pigments#251]
So i have a problem. Pigments in Atom doesn't works any ideas why?

**Comment by C-Bouthoorn** [comment]
Nope, I don't have any idea. Maybe if you give more information, we can investigate this matter. (Pigments version, Atom version, operating system?)

**Comment by C-Bouthoorn** [comment]
We're now more than a month later, so I guess the error didn't persist. If that still is the case though, let us know so we can re-open this issue.
