### ISSUE TITLE
highlighting on backticks

### ISSUE THREAD

**Issue by duivvv** [abe33/atom-pigments#252]
Colors don't show up if I'm using backticks in my code

With single quotes:

![single](https://d17oy1vhnax1f7.cloudfront.net/items/2M1G2j2l0t2Q2X0A2w3f/Screen%20Shot%202016-12-04%20at%2010.00.58.png?v=3e83158a)

With backticks:

![backticks](https://d17oy1vhnax1f7.cloudfront.net/items/2s3E1x3X190j1u07220A/Screen%20Shot%202016-12-04%20at%2010.00.48.png?v=ceb07bcd)

**Comment by C-Bouthoorn** [comment]
I suppose this is because `'#fff'` is in the `string.quoted.single.js` scope, and the backticked one is in the `string.quoted.template.js` scope. Let me investigate.

**Comment by C-Bouthoorn** [comment]
Should be fixed in https://github.com/abe33/atom-pigments/pull/267

**Comment by duivvv** [comment]
Thanks :)
