### ISSUE TITLE
Atom Pigments not working - OSX 10.10 Yosemite

### ISSUE THREAD

**Issue by ghost** [abe33/atom-pigments#254]
In styles/pigments.less: Style elements within text editors using the `atom-text-editor::shadow` selector or the `.atom-text-editor.less` file extension.
If you want to target overlay elements, target them directly or as descendants of `atom-overlay` elements.

Currently on OSX 10.10 Yosemite. Any ideas?

**Comment by C-Bouthoorn** [comment]
If I remember correctly, `::shadow` is deprecated now? Feel free to correct me though, as I don't really understand your question.

**Comment by C-Bouthoorn** [comment]
Seems to have been fixed. Closing
