### ISSUE TITLE
Sass default color functions work incorrectly in Palette view

### ISSUE THREAD

**Issue by ierhyna** [abe33/atom-pigments#257]
Hello,
Thank you for a really useful plugin!

I found an issue with Sass default color functions (transparentize, darken, and lighten) in Palette view. It any of these functions is used, the color is black in the Palette, but has the proper color in the editor.

Please see the screenshots attached.

![image](https://cloud.githubusercontent.com/assets/4463110/21319028/9876236c-c61c-11e6-837a-575b9ad25319.png)

![image](https://cloud.githubusercontent.com/assets/4463110/21319045/a37da4d8-c61c-11e6-8a57-2cc693d50f1c.png)

**Comment by C-Bouthoorn** [comment]
Failed to reproduce on my system with Atom Beta (1.14.0-beta0) and Pigments 0.38.0, assuming some code you didn't show.

![screenshot from 2017-01-14 23-04-37](https://cloud.githubusercontent.com/assets/10348289/21958415/dfb0cdd6-daad-11e6-9945-4677569e6c8a.png)

Could you please share your report with us, so we could investigate where the problem might be? (Palette > Pigments: Report)? Thanks

**Comment by C-Bouthoorn** [comment]
Seems to have been fixed. Closing
