### ISSUE TITLE
Pigment not working for source.js extension

### ISSUE THREAD

**Issue by nobalmohan** [abe33/atom-pigments#258]
I use atom to build my mobile app in react native. All styles are written in **styles.js** files. Since it's a JS extension. Pigment won't show up the colors. I added the same in Setting -> source.js too. But, it won't be recognized.

**Comment by abe33** [comment]
Hi @nobalmohan, do you have some sample code I can use to make some tests?

**Comment by nobalmohan** [comment]
A sample style sheet from my rect-native project. Here backgroundColor will not hightlight the pigments. 

```
const React = require('react-native');

const { StyleSheet } = React;

module.exports = StyleSheet.create({
  facebookBtn :{
    backgroundColor: '#3b5998',
    borderRadius: 5
  },
  skipBtn: {
    backgroundColor: '#fff'
  },
  skipBtnText: {
    color: '#666666'
  }
});
```

**Comment by C-Bouthoorn** [comment]
I failed to reproduce this issue on my system. Could you please share your Pigments report? (Palette -> Pigments: Report)

Maybe it could be useful to notice that the file I'm using in the screenshot is using `language-javascript` and has the `.source.js` scope. I know that packages for React exist, which might change this language or scope. Your report might give us more knowledge about this.


![screenshot from 2017-01-14 22-31-27](https://cloud.githubusercontent.com/assets/10348289/21958207/34ca9e46-daa9-11e6-8f98-e55434763ca6.png)

**Comment by nobalmohan** [comment]
@C-Bouthoorn I updated my atom and packages few days and go. I can see the colours now. I don't know what caused the issue. You can close this issue. You need any config information. I will add it too.

**Comment by C-Bouthoorn** [comment]
If everything is fixed in the latest version, then I think we don't need more information (such as your config) and thus can safely be closed. Thanks for your help! :smile:
