### ISSUE TITLE
Pigments doesn't show colors

### ISSUE THREAD

**Issue by kissa1001** [abe33/atom-pigments#260]
I have pigments installed and then in my project it doesn't show colors, instead I see squares.[
<img width="473" alt="screen shot 2016-12-31 at 12 39 15 am" src="https://cloud.githubusercontent.com/assets/15070517/21576775/c9ec030c-cef1-11e6-880c-52e22a133536.png">
](url)

**Comment by FieryCod** [comment]
Try to install different version of a pigments. Firstly uninstalll your package then:

**Try**

1. `apm install pigments@0.36.0` 
 If there is still something wrong try to uninstall pigments and then install:
2. `apm install pigments@0.38.0`
 If there is still something wrong try to uninstall pigments and then install:
2. `apm install pigments@0.35.0` 

I hope i helped.

**Comment by arxpoetica** [comment]
This is definitely broken. The plugin is effectively rendered useless until this is fixed.

**Comment by C-Bouthoorn** [comment]
Could you please share the Pigments report with us, so we can see where it could go wrong?

This report can be found under `Pigments: Report` in the Palette (Defaults to `Ctrl-Shift-P`)

**Comment by mradziwon** [comment]
I had a similar problem. It was caused by custom Theme.

**Comment by C-Bouthoorn** [comment]
Seems to have been fixed. Closing
