### ISSUE TITLE
Colors found twice and displayed as words below variables

### ISSUE THREAD

**Issue by Kadrian** [abe33/atom-pigments#262]
Hi, I've got
* atom 1.12.9
* atom-pigments 0.38.0.

<img width="280" alt="bildschirmfoto 2017-01-09 um 21 57 47" src="https://cloud.githubusercontent.com/assets/1403093/21783257/d315d184-d6b6-11e6-8fc2-bb77833d08b6.png">

Any idea why this is happening?

I also noticed that pigments finds all colors twice on consecutive lines:

<img width="589" alt="bildschirmfoto 2017-01-09 um 22 00 13" src="https://cloud.githubusercontent.com/assets/1403093/21783306/0a3ae96a-d6b7-11e6-983a-d1fbf45d7fca.png">

even though they were only defined once:

<img width="242" alt="bildschirmfoto 2017-01-09 um 22 01 01" src="https://cloud.githubusercontent.com/assets/1403093/21783328/24642478-d6b7-11e6-90c9-1f19dccf4057.png">

**Comment by C-Bouthoorn** [comment]
Could you share your report for pigments?

Would you please open the palette (default `Ctrl-Shift-P`) and search for `Pigments: Report`. Click that and copy the resulting file here, so we can see where it could go wrong.

**Comment by Kadrian** [comment]
I just had to replace my macbook because of a broken spacebar. Now I'm unable to reproduce the error on the new one (now using Atom 1.13.0, pigments still at 0.38.0). Now everything is working fine 🙈

**Comment by C-Bouthoorn** [comment]
I'll regard it as closed then. If the error ever arises again, I'll reopen it :smile:
