### ISSUE TITLE
Enhancement: Recommend a color from palette given input color

### ISSUE THREAD

**Issue by admosity** [abe33/atom-pigments#265]
I have a use case where I would like to input a color and possibly get a list of colors sorted by how similar it is. Maybe calculated via a simple distance formula?

I am working with some designs that have colors close to the defined palette, but are off a bit.

**Comment by C-Bouthoorn** [comment]
Maybe slightly related to https://github.com/abe33/atom-pigments/issues/242 ?

**Comment by admosity** [comment]
I was thinking adding another input box to the top here to sort the list:

![image](https://cloud.githubusercontent.com/assets/4655972/22023039/8e5f92b4-dc92-11e6-9014-29bd91b5756f.png)

Maybe add another option to sort colors by similarity to color inputted:
![image](https://cloud.githubusercontent.com/assets/4655972/22023073/aebce6d8-dc92-11e6-8f1e-fc09a2a1b8f3.png)

**Comment by abe33** [comment]
Hi there, do you have an idea of what kind of criteria would be used to check for similarities? I mean distance is not a clear criteria when it comes to colors, is it distances between channel, between number representations, between hues, etc.
