### ISSUE TITLE
Pigments not working

### ISSUE THREAD

**Issue by Divy-Jain** [abe33/atom-pigments#272]
![screenshot 42](https://cloud.githubusercontent.com/assets/23337526/22180873/a5271c14-e0a3-11e6-8bad-fe1dbab9ca1c.png)

I found this great package and decided to install it. But it seems it is not working. Your help would be appreciated and thanks in advance.

**Comment by abe33** [comment]
Which version of Atom are you running?

**Comment by Divy-Jain** [comment]
It started after a restart of Atom.

Thanks for your help.


________________________________

**Comment by C-Bouthoorn** [comment]
That doesn't answer the question; which version of Atom are you running?
