### ISSUE TITLE
Stop "Pigments successfully reloaded" notification from showing

### ISSUE THREAD

**Issue by alexcroox** [abe33/atom-pigments#277]
I'm using the Project Manager package which allows me to quickly switch, in the same window, between folders/projects.

When I do however I am greeted by a giant notification that doesn't auto close and requires manual action from me to remove it.

A minor annoyance of course, but if we could disable it, it would be less frustrating switching between projects all day :)

![https://cl.ly/j4xw/Screen%20Shot%202017-02-09%20at%2011.31.34.png](https://cl.ly/j4xw/Screen%20Shot%202017-02-09%20at%2011.31.34.png)

**Comment by doar2016** [comment]
There's two items that can be turned off in the Pigments settings.

1. Dismissable Reload Notifications
2. Notify Reloads

**Comment by alexcroox** [comment]
I'm an idiot, I must have been looking in the wrong package settings, apologies!
