### ISSUE TITLE
Way to override .gitignore file?

### ISSUE THREAD

**Issue by aaronbarker** [abe33/atom-pigments#28]
It appears that when I do a "find colors" that pigment also ignores files that are included in the .gitignore file.  We have some styleguide files that declare our colors in a internal bower package and so we have those files in the .gitignore so that they don't get checked in, but we want those colors available to pigment.

I have confirmed that if I remove the folder from .gitignore that pigment finds the colors, and if I put it back it doesn't find them.  Is there a way to have pigment include a folder that is listed in the .gitignore?

**Comment by abe33** [comment]
Thanks for the feedback, that make totally sense. I'll see how I can handle this case, maybe through a setting like `includedNames` that would override vcs ignored names and pigments own ignored names.

**Comment by abe33** [comment]
I forgot to reply, but now there's a new feature called project settings (available through the command palette) that allow you to ignore the global settings on a per-project basis. So I think I can close this issue now :)

**Comment by aaronbarker** [comment]
@abe33 This works great, thank you!
