### ISSUE TITLE
Pigment inside JS file causes error

### ISSUE THREAD

**Issue by jakejarrett** [abe33/atom-pigments#281]
Not sure *why* it's running on my JS file, But whenever i edit a jsdoc comment (Which will be colored by atom itself, not sure if that will conflict)

It returns this error (Truncated directory)
```js
{atom_dir}\resources\app.asar\src\package.js:543
Uncaught TypeError: Cannot read property 'pigmentsViewProvider' of null
```

*OS* - Windows 10
*Atom version* - 1.14.3
*Pigments version* - 0.39.0

The JSDOC Plugin i'm using is *docblockr* (again, unsure if it would conflict)

**Comment by C-Bouthoorn** [comment]
Seems not to be reproducible. Closing
