### ISSUE TITLE
Native CSS variables not highlighting

### ISSUE THREAD

**Issue by pgrantmartello** [abe33/atom-pigments#283]
![image](https://cloud.githubusercontent.com/assets/22772150/23310497/c0826152-fa80-11e6-867a-2266f0517ca5.png)

I feel like this should highlight my background-color property, but that's not happening.

**Comment by pgrantmartello** [comment]
I suppose this gets complicated when considering scope into a class or into a media query or something. Not sure if that's a blocking issue or if we just assume some caveats and make an educated guess.

**Comment by turnipjs** [comment]
I do not have this issue, It works fine for me. Maybe this has been fixed since feb 2017?

**Comment by C-Bouthoorn** [comment]
I think so too. I'll close it
