### ISSUE TITLE
Works with others file extensions

### ISSUE THREAD

**Issue by artemgurzhii** [abe33/atom-pigments#284]
Should not highlight files, which not relate to CSS.
Example with ruby:
<img width="166" alt="screen shot 2017-03-02 at 00 58 57" src="https://cloud.githubusercontent.com/assets/13109164/23485297/7eae0256-fee3-11e6-9e3d-1070c96b4e9b.png">

**Comment by C-Bouthoorn** [comment]
Should be able to fix in the option menu. Closing
