### ISSUE TITLE
pigments palette doesn't work

### ISSUE THREAD

**Issue by kiritotwoswords** [abe33/atom-pigments#291]

**Comment by C-Bouthoorn** [comment]
Could you please specify more? I.e.: The version number of Atom, Pigments, Node and which OS you are running?

**Comment by SamdeVega** [comment]
Maybe it's the same reason exposed here https://github.com/abe33/atom-pigments/issues/293

**Comment by C-Bouthoorn** [comment]
Closing due to a lack of information for a long period
