### ISSUE TITLE
Pigments does not seem to act or react at anything....

### ISSUE THREAD

**Issue by TigersWay** [abe33/atom-pigments#293]
Just installed Pigments (0.39.1)....
Did not get any specific message of notification.
And it just does not do anything, no highlighting, no auto-completing, no notification on "Pigments Reload", empty pane on "Pigments find-colors"....

Atom Win32 / Windows 7 x64
```
atom --version
Atom    : 1.15.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

```
Thanks

**Comment by C-Bouthoorn** [comment]
Maybe a silly question; but did you try restarting Atom?

**Comment by TigersWay** [comment]
It never is 😁
But yes I did. Tried also disable and re-enable without success or any reaction.
Right now it has been enabled for 4 days of work and... Just nothing.

**Comment by SamdeVega** [comment]
Pigments doesn't paint code in document if you are working in a new one. I suppose that the reason could be that plugin reads any metadata from document when you open it.
Try to save the file first, close it and reopen it again.

**Comment by TigersWay** [comment]
Just made another install on a second computer: Window 7 x64 and Atom x64 this time. Added pigments before anything else and tried (Restart, etc): Exactly same result, pigments does not react.

The only thing in common is that both installations are in "**portable mode**". Any idea?

**Comment by TigersWay** [comment]
Just having "fun"!!!
New install from scratch on a freshly installed Windows 10 x64, Atom 1.17.0 x64....  As you may guess the next two are still valid:
- Pigments still does not react in any way
- I'm still in Portable mode.

**Comment by C-Bouthoorn** [comment]
Could you try running without portable mode and see if the problem persists?

**Comment by TigersWay** [comment]
Don't really intend to "shot myself in the foot":-)

Despite that, I may try on a next install... and check if it is portable mode and only that.

**Comment by lost-anjarrett** [comment]
Hi ! 
I had a similar problem, but I figured out that was because I had too many css files in my project folder (too many projects loaded in tree view). I removed all and just add the project i'm working on right now and pigments works fine. 
Hope this can help...

**Comment by C-Bouthoorn** [comment]
Closing in favour of the [master post](https://github.com/abe33/atom-pigments/issues/351).

**Comment by PedroMouta** [comment]
> Pigments doesn't paint code in document if you are working in a new one. I suppose that the reason could be that plugin reads any required metadata from document to work when you open it. Try to save the file first, close it and reopen it again.

This is it! Worked for me, just save and close the file, re-open. If needed, completely remove entire folder from Atom and re-open. Has solved the issue.
