### ISSUE TITLE
Makes editor lag.

### ISSUE THREAD

**Issue by kasiraket** [abe33/atom-pigments#296]
When jumping between lines of code - Atom just freezes for a second or so.

**Comment by Memnarch1113** [comment]
I have this same issue. Confirmed with Package Cop that Pigments is the troublemaker!

**Comment by SureWeb** [comment]
Same here. I uninstalled Pigments and now there is no lag.

**Comment by garrettw** [comment]
Same. I can't tell if it's the size of my CSS file (or the number of colors in it) making it lag... but I have noticed that high CPU usage is the culprit when it slows down.

**Comment by garrettw** [comment]
possible duplicate of #275

**Comment by C-Bouthoorn** [comment]
Indeed a duplicate of #275
