### ISSUE TITLE
Pigments in Comments

### ISSUE THREAD

**Issue by SamdeVega** [abe33/atom-pigments#299]
First, I don't know if this is working as it is suposed to do.
Pigments is applying its functionality on commented code.
In my case, some words like 'red' could have another meaning if I am writting a comment in my mother tongue.
This is a particular case. It is not relevant for another color formats (hex, rgb and so on)

Regards.

![pigments_bug](https://cloud.githubusercontent.com/assets/10880609/25432166/4c4a5d1e-2a7b-11e7-9b7d-0a34b969fe65.PNG)

**Comment by C-Bouthoorn** [comment]
As far as I know, Pigments doesn't look at the actual code. Colors will be shown in code, strings, comments, etc. I do remember something about not parsing words (like red), but only rgb/hsv codes.

**Comment by abe33** [comment]
You can probably find an answer to that issue in the REAME: https://github.com/abe33/atom-pigments#defining-where-pigments-applies
