### ISSUE TITLE
Weird autocomplete-plus suggestions

### ISSUE THREAD

**Issue by dsandstrom** [abe33/atom-pigments#3]
With package disabled:
![2015-04-22_1728](https://cloud.githubusercontent.com/assets/1400414/7288350/3cd2b646-e915-11e4-880a-b26724c2a5c1.png)

With package enabled:
![2015-04-22_1727](https://cloud.githubusercontent.com/assets/1400414/7288360/5271d5f4-e915-11e4-957b-7e82dd4d03d7.png)

I'm not sure what the intended behavior is, but:
- the suggestions don't seem right.  It's only suggesting sass variables.  And the hint text is what they are assigned to. 
- the window is wider which is probably caused by a long variable.

**Comment by abe33** [comment]
@dsandstrom Yeah, you're right, there's a problem with current autocomplete, using fuzzy-matching isn't really the best course of actions, I should really use a more stricter filtering function. I think I'll push a patch in today for that.
