### ISSUE TITLE
Add support for CSS variables

### ISSUE THREAD

**Issue by awayken** [abe33/atom-pigments#30]
Given that technologies like [PostCSS](https://github.com/postcss/postcss) and [cssnext](http://cssnext.io/) allow us to use [CSS variables](http://www.w3.org/TR/css-variables/) in stylesheets today, it would be nice to see Atom Pigments extend support for those types of variables. Are there any plans to add support like this?

**Comment by abe33** [comment]
This is sadly not as simple as it sounds, CSS variables aren't like pre-processors variables, their value depends on the context which means one cannot evaluate the value that a variable will hold without knowing the DOM structure onto which it'll be applied. 

For instance: 

```css
node_a { --color: red; } 
node_b { --color: green; } 
node_c { color: var(--color); }
```

What is the value for `val(--color)` then?

It's `red` when `node_c` is a child of a `node_a` element and `green` when child of a `node_b` element.

That means that only a browser with full knowledge of the DOM and the CSS that applies can compute that value.

**Comment by awayken** [comment]
That's a good point. At it's simplest, you could probably limit support to variables declared under `:root`. Would that be a simple enough implementation?

Truth be told, I wasn't even aware of the cascading functionality until you mentioned it. It seems like a potential minefield for parsers and authors alike.

**Comment by esiao** [comment]
Updating this as I started using PostCSS too. With the module [PreCSS](https://github.com/jonathantneal/precss) you can use Sass syntax. Would be nice to have CSS support for Pigments for this case since it's replicating what is done with Sass files.

**Comment by abe33** [comment]
@esiao It's clearly more in the scope of what pigments can do. Actually the only thing that should not work with PreCSS files is the project-wide palette, as it currently excludes `*.css` files, but the change should not be too complicated so I'll give it a try soon.

**Comment by esiao** [comment]
@abe33 Thanks that would help a lot actually.

**Comment by abe33** [comment]
BTW @esiao, have you tried to add `**/*.css` in the `Source Names` setting? It should works out of the box without needing a patch.

**Comment by esiao** [comment]
No I hadn't the curiosity to check if it was possible in the settings.
I actually had to quit and relaunch atom for this to take effect. But it's nicely working big thanks.

**Comment by abe33** [comment]
> I actually had to quit and relaunch atom for this to take effect
Oh, looks like I missed to observe the config.

**Comment by AntonTrollback** [comment]
+1 :)

**Comment by abe33** [comment]
@esiao: I just reviewed my suite and it should update when the setting is changed, it just need a bit of time to scans the new files but that's all.

@AntonTrollback: +1 for what?

**Comment by AntonTrollback** [comment]
sorry, just bumping the issue. this feature would be great

**Comment by abe33** [comment]
As I said, only a browser can accurately evaluate css variables, as it depends on styles cascading. Even the PostCSS documentation is quite clear about that: 

> We strive for the most complete transformation but we/no plugin can achieve true complete parity according to the specification because of the DOM cascade unknowns.

In their playground I just tried one of the simplest use case of css variables: 

```css
.foo {
	--color: blue;
}

.bar {
	color: var(--color);
}
```

Which gives: 

```css
.bar {
	color: undefined;
}
```

That's a pretty simple case and yet PostCSS, as a specialized utility, can't evaluate that properly. A browser, however, is able to tell that `.bar` color should be blue when `.bar` is a child of `.foo`.

Pigments have always been thought as a small utility, meant to be able to perform its job with little to no knowledge of context (it can't and probably never will handle less/sass/stylus scopes properly). It grew in complexity with the support of project's variables, and I think I reached a peak with that feature as I had to rewrite the entirety of the parsing/evaluation process to make it perform nicely even with large files/project. 
I don't really see how I can plug something like PostCSS in pigments without having to break the whole code again, and I have no guarantee that it'll works correctly and without killing the performances.
If someone want to give it a try and submit a PR I'm open to discuss it, but in my point of view the risk far outweigh the benefit.

**Comment by AntonTrollback** [comment]
> in my point of view the risk far outweigh the benefit.

Alright. Yep, I agree

**Comment by corintho** [comment]
Sorry to bring the topic back up again, but would it be possible to at least try to parse variables assignments to assemble the Project Palette? I think that should not be a big issue, nor a performance bottleneck and I think would be a great addition to have. I'm willing to try this if that seems reasonable.

**Comment by abe33** [comment]
@corintho Looks feasible. OTOH latest Pigments version introduce some new services to extend Pigments variables and colors expressions. I still have to write proper documentation for that, but if some want to give it a try it can take a look at how I create variable expressions: https://github.com/abe33/atom-pigments/blob/master/lib/variable-expressions.coffee

**Comment by cedriceberhardt** [comment]
While having the representation of the color with dot or in the gutter, it is also maybe possible to show all the related colors. For the example above it would be green and red. And then show the selector with a tooltip?

And I don't think that we will have thousand of --color variables in our code. I really think people names variables properly, like nobody do `var variable = 32;` for example. Except for `i` maybe ;-)

**Comment by abe33** [comment]
I'll start a first, naïve, implementation and we'll see how it turns out. I'm not really sure how useful or buggy it'll be so I'd rather test things directly. Stay tuned.

**Comment by abe33** [comment]
Ok, so I just published 0.23.0 with a simple implement that matches things like `--foo: <color>;` and then highlights instances of `val(--foo)`. But you'll have to add `**/*.css` in the source names setting (I did not want every user to see their loading time increase due to pigments scanning all the CSS for variables as well).

**Comment by awayken** [comment]
@abe33 To clarify, does it look for `val(--foo)` or `var(--foo)`? I'm having issues seeing this work, and I'm trying to figure out if it's just me or not.

**Comment by awayken** [comment]
@abe33 First of all, thank you so much for putting effort into this feature!

Second of all, it does look like you're searching for `val()` but it should be `var()`: https://www.w3.org/TR/css-variables/#using-variables

If I use `val()` like you have it, then I get the color highlighting. :fireworks: :tada: :trophy: :+1: Changing `val()` to `var()` should work perfectly.

Third of all, one thing I had issues with (even using the `val()` syntax) was passing a custom property to the `color()` method: `background: color(var(--color-warning) alpha(10%));` It didn't highlight anything.

Worst case scenario, it'd be nice for `var(--color-warning)` to highlight. Best case, the whole line would highlight with the rendered version of the color (10% alpha of my warning color).

I'm not sure how complicated this second part is, so maybe it warrants an entirely different ticket. Here's more information on `color()`, if it helps: https://drafts.csswg.org/css-color-4/#modifying-colors

**Comment by abe33** [comment]
Hi @awayken, thanks for the heads up, I think I had a really hazy brain when I coded that `val()` thing. I'll patch that asap. As for the color(...) thing, I'll take a look, but since CSS `color` function is [supposed to be supported](https://github.com/abe33/atom-pigments/blob/master/spec/color-parser-spec.coffee#L509) it may be just a matter of tweaking the regexp to allow `var()` in it.

**Comment by abe33** [comment]
It should be better with 0.23.1, let me know if you still find some issues.

**Comment by awayken** [comment]
@abe33 At first, it didn't seem to be working. I closed all my Atoms and reopened them, and I was still getting the old behavior. I double-checked that my package was updated. I even browsed the code of the package and saw where you'd corrected the issue and added the new tests. I was a little baffled. Then I went back to the CSS file where I declare most of my variables, went back to the example I mentioned before, and all the highlighting worked!

I'm not sure what the deal was. A local cache maybe? I'm pretty sure my issue stems from testing before, so it's unlikely others will run into it. And the most important part is that it's working beautifully.

Thanks so much for your help on this, @abe33! My CSS is now filled with colors once again.

**Comment by abe33** [comment]
> I'm not sure what the deal was. A local cache maybe?

Oh right, I should have bumped the markers version to invalidate the serialized color markers. In that case closing/opening a file should be enough (since the previously serialized markers will be destroyed), but I should have thought of that before shipping :sweat_smile:.

**Comment by cedriceberhardt** [comment]
@abe33 First of all, thank you!

```
node_a { --color: red; }
node_b { --color: green; }
node_c { color: var(--color); } // green
node_a node_d { color: color(var(--color) alpha(50%)); } // green
```
In the example above and if I understand well the W3C drafts, node_d should be red because he is dependent from node_a. But here it's green.

**Comment by abe33** [comment]
@cedriceberhardt As I already stated several time in this thread, I was relunctant to implement CSS variables support for the very reason that nobody except a browser can guess what is the color to apply  because you have to be aware of the DOM onto which the CSS applies. 

I don't really plan to make Pigments support this kind of thing as it's: 

1. not reliable: any implementation I can provide will never match how a browser works and will always fails at some point (see how a specialized utility like postCSS is very wary about that too)
2. too complex: any implementation will need parse css rules selector, then it must compute specificity (not really hard but still, it adds code to maintain), and it would require another complete rewrite of the pigments model just to support this feature (which is, AFAIK, not production-ready anyway)

&lt;rant>I just never understood why the CSSWG ended up with this shit of a spec. Once again, instead of looking at what problems developers had and what solutions they came up with, they decided to push for an unrequested, overcomplicated feature. I can see where this features can be useful, but it's almost impossible to build tooling around that and using it without too much side-effect requires god-like abities.&lt;/rant>

**Comment by cedriceberhardt** [comment]
@abe33 I understand. I was just guessing you changed your mind as this topic is a bit old ;)

**Comment by abe33** [comment]
I did change my mind a bit, mostly aiming for the low hanging fruit, but I don't see how I could easily go further than that without spending a huge amount of time. If someone wants to make a PR I'll gladly review it, but as I have already my hands quite full with keeping all the packages I maintain up to date with Atom and fixing bugs here and there that I can't promise I'll be able to spend a lot of time pushing this feature.

**Comment by awayken** [comment]
If everyone is satisfied, I feel like this issue can be closed for good. Anyone object?
