### ISSUE TITLE
Not recognising new colours

### ISSUE THREAD

**Issue by nervewax** [abe33/atom-pigments#302]
```
macOS Sierra 10.12.4
Atom 1.16.0
Pigments 0.39.1
```

`.scss` files that previously displayed colours break after changing.
New colours no longer display / work.

![may-10-2017 12-39-24](https://cloud.githubusercontent.com/assets/7255911/25896859/baff43ac-357d-11e7-9ddc-5feeedf57de6.gif)

I saw in a previous issue that you may need a Stack Trace. I'm not sure how to generate one for pigments, if you let me know I'll provide one.

I've reinstalled pigments and atom.
Tried disabling all packages except pigments. (including using default themes)
I also tried View > Developer > Reload Window

**Comment by courtneygives** [comment]
I may be having the same issue. 

<img width="497" alt="screen shot 2017-07-03 at 16 05 28" src="https://user-images.githubusercontent.com/10428239/27807889-8c9cda2c-6009-11e7-9115-de478547d194.png">

<img width="494" alt="screen shot 2017-07-03 at 16 10 01" src="https://user-images.githubusercontent.com/10428239/27807970-21619332-600a-11e7-867c-1323e31e99fd.png">

Mac OS Sierra 10.12.5, Atom 1.13.0, Pigments 0.39.1

**Comment by courtneygives** [comment]
Okay, as soon as I report the issue, it stops happening. Of course. Possibly just me, but maybe the extra data point helps. Apologies.

**Comment by Gioyik** [comment]
I confirm this happening to me the first minutes after installing pigments. I write a new hex color and it doesn't get updated as expected. After a few minutes it start working as it should, maybe that's what happened to @courtneygives in first place. Seems like a case where pigments is installed by first time and takes time to start recognizing files and fetching the correct colors.

**Comment by nervewax** [comment]
I've not seen this issue happening in a while personally, i'll close this but feel free to reopen if it's a problem for anyone else.
