### ISSUE TITLE
How refresh variable colors?

### ISSUE THREAD

**Issue by Nath-sticky** [abe33/atom-pigments#303]
Hi guys

I have an annoying issue. I had change the color code of my variable but they still appears with the old colors... How "delete the cache"? or refresh the value of variable?

Thanks :)

(Sorry for my poor english :/)

**Comment by C-Bouthoorn** [comment]
Go to the Palette, then execute `pigments:reload`. However, Pigments should do this automatically when you change the colour, so it seems something else is wrong. Could you show us a (piece of) code that's causing this issue, or is it persistant across all files for you? Also, what OS are you using? Thanks 😄

**Comment by C-Bouthoorn** [comment]
Closing due to lack of information
