### ISSUE TITLE
Pigment is not coloring in atom 1.17-dev-5

### ISSUE THREAD

**Issue by v3ss0n** [abe33/atom-pigments#305]
![screenshot_20170515_014030](https://cloud.githubusercontent.com/assets/419606/26037060/56b09b66-3911-11e7-99b2-f3384b53af63.png)

I had waited a few hour but no coloring yet.

**Comment by C-Bouthoorn** [comment]
Could you maybe share more information? OS, Pigments version, Atom version, Node version?
The following commands could help you: `uname -a`; `apm --version`; `atom --version`; `apm view pigments`

**Comment by will-stone** [comment]
Not colouring in Atom 1.18 beta either.

    Darwin OSTML0196111 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64

    apm  1.18.1
    npm  3.10.10
    node 6.9.5 x64
    python 2.7.10
    git 2.11.0

    Atom    : 1.18.0-beta0
    Electron: 1.3.15
    Chrome  : 52.0.2743.82
    Node    : 6.5.0

    pigments
    ├── 0.39.1
    ├── https://github.com/abe33/atom-pigments
    ├── A package to display colors in project and files.
    ├── 1746537 downloads
    └── 2930 stars
    
    Run `apm install pigments` to install this package.

**Comment by guywald1** [comment]
+1

**Comment by guywald1** [comment]
I am also not seeing colors in Atom 1.18.0-beta0

```
Darwin G-MBP 16.5.0 Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64 x86_64

apm  1.16.1
npm  3.10.5
node 6.9.5 x64
python 2.7.12
git 2.10.2

Atom    : 1.18.0-beta0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

pigments
├── 0.39.1
├── https://github.com/abe33/atom-pigments
├── A package to display colors in project and files.
├── 1747591 downloads
└── 2934 stars
```

P.S. Great package. Thank you so much :)

**Comment by ninthart** [comment]
yep, it's stopped working for me in Atom-Beta 1.18.0-beta0 too. Details below:

```
Darwin Brads-iMac-2.local 16.5.0 Darwin Kernel Version 16.5.0: Fri Mar  3 16:52:33 PST 2017; root:xnu-3789.51.2~3/RELEASE_X86_64 x86_64

apm  1.18.1
npm  3.10.10
node 6.9.5 x64
python 2.7.13
git 2.11.0

Atom    : 1.18.0-beta0
Electron: 1.3.15
Chrome  : 52.0.2743.82
Node    : 6.5.0

pigments
├── 0.39.1
├── https://github.com/abe33/atom-pigments
├── A package to display colors in project and files.
├── 1747941 downloads
└── 2935 stars
```

I hope this is an easy fix as Pigments is one of the best packages on Atom, and I'm missing it! Thanks for taking a look at this…

**Comment by camloken** [comment]
Pigments broke for me on Mac.
MacOS Sierra 10.12.4
Atom 1.18.0-beta0

**Comment by v3ss0n** [comment]
Still broken at releases 1.17

**Comment by pingshunhuangalex** [comment]
This bug is fixed in `Atom 1.18.0-beta1` now.

**Comment by ninthart** [comment]
yep, confirmed working in Atom Beta 1.18.0-beta2 🎉

**Comment by v3ss0n** [comment]
Thats good , closing since it is working in beta2
