### ISSUE TITLE
Color Palette Blank

### ISSUE THREAD

**Issue by nickfmc** [abe33/atom-pigments#31]
Opening up the Palette within Sass based project and color palette shows nothing at all.  used to work in previous versions. Of note the find color function works as expected.

0.7.2 - Win8.1

**Comment by abe33** [comment]
Hi @nickfmc, thanks for the report, I didn't notice an issue and all tests are still passing. 

A few questions: 

Do you see the palette tab but with no color or is there no palette tab at all?
In the case you see the palette tab but with nothing in it, does triggering `pigments:reload` command help?
Is there an error appearing in the console?
Do you happen to have deleted/renamed a file in your project at some point? (there's still some gray area I need to cover when it comes to changes in the file structures)

**Comment by nickfmc** [comment]
The palette is there however no colors appear. pigments:reload doesn't help. No errors in the console no.  I opened a new project and my palette DOES show, so I believe it is the renaming of files issue as I am sure I have renamed a file or two over the course of the project.

**Comment by abe33** [comment]
I think I roughly figured the problem, it's probably related to the serialized state of the project still referencing the previous paths. I'll to fix that soon, in the mean time you can probably fix this by clearing the Atom state for this project in the `~/.atom/storage` directory. I explain quickly how to do that [in the atom forum](https://discuss.atom.io/t/atom-is-loading-old-version-of-a-file-even-after-a-restart/17432/3?u=abe).

**Comment by onetrev** [comment]
I have this issue too. Should I be concerned though, I cleared out my `~/atom/storage/` folder of all the editor-***** files, and still my Palette is empty on some projects.

**Comment by abe33** [comment]
Hi @onetrev, Could you tell me what your config is? Things like what values you have in `sourcesNames`, `ignoredNames` in the pigments settings, `ignoredNames` in the core settings. Also, what versions are you using (Atom, Pigments). 
Also, can you tell me a bit about the kind of project where the palette is empty? Like how many files is there, are you using vendor dependencies like bootstrap & co?

**Comment by onetrev** [comment]
Hello! Thanks for the quick reply.

All Pigment settings are default, so nothing has been added there. For `ignoredNames` all I havead
`*.sql`

For the projects that have empty palettes there is nothing to really differentiate them. They are start with the same base WP theme I have created that is very basic. To begin with the Palette seems to work in my base theme, but at some point sometimes it goes off the rails and no longer shows. Definitely no bootstrap added (ugh, bloatstrap as I call it!).

Everything is .scss based. I have my main.scss file, then in child folders I have all the `@import`.

Versions:
Atom - 0.209.0
Pigments - 0.7.2

Anything else you need please let me know. Sorry I can't determine right now what is going this glitch. Thanks for helping!

**Comment by abe33** [comment]
I'm really not sure about what could go wrong, I added a `catch` trap to the `show palette` promise in v0.7.3 that will log the error in the console. Let me know if there's an error when opening the palette.

**Comment by onetrev** [comment]
Well in good news, for me at least, the projects that had blank palettes are now working again. Not sure if it was the Atom 0.210 update or what, but it's working in all projects. If I notice any issue though for sure will check out console, thanks!

**Comment by nickfmc** [comment]
Update Works For me! Thanks.

**Comment by abe33** [comment]
Glad to hear that, let me know if you still get problems.
