### ISSUE TITLE
FATAL ERROR: deserialize context Allocation failed - process out of memory

### ISSUE THREAD

**Issue by borishere** [abe33/atom-pigments#311]
I get this error in Atom 1.18.0-beta0

![screenshot_1](https://cloud.githubusercontent.com/assets/4622497/26224835/deaf08b8-3c2c-11e7-9c51-82cf5523499a.png)

**Comment by surdu** [comment]
When I enable this package, I see an ~1Gb memory spike :(

**Comment by C-Bouthoorn** [comment]
Could you give us an indication of how big those projects are?

**Comment by C-Bouthoorn** [comment]
Also, this is the same problem as https://github.com/abe33/atom-pigments/issues/308, so closing.
