### ISSUE TITLE
Deprecated selector in `pigments\styles\pigments.less`

### ISSUE THREAD

**Issue by mernorthzide** [abe33/atom-pigments#312]
In `pigments\styles\pigments.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor::shadow .pigments-native-background .region,
atom-text-editor .pigments-native-background .region,
atom-text-editor::shadow .pigments-native-background-in-selection .region,
atom-text-editor .pigments-native-background-in-selection .region` => `atom-text-editor.editor .pigments-native-background .region,
atom-text-editor .pigments-native-background .region,
atom-text-editor.editor .pigments-native-background-in-selection .region,
atom-text-editor .pigments-native-background-in-selection .region`

* `atom-text-editor::shadow .pigments-native-background .region:before,
atom-text-editor .pigments-native-background .region:before,
atom-text-editor::shadow .pigments-native-background-in-selection .region:before,
atom-text-editor .pigments-native-background-in-selection .region:before` => `atom-text-editor.editor .pigments-native-background .region:before,
atom-text-editor .pigments-native-background .region:before,
atom-text-editor.editor .pigments-native-background-in-selection .region:before,
atom-text-editor .pigments-native-background-in-selection .region:before`

* `atom-text-editor::shadow .pigments-native-background .region:after,
atom-text-editor .pigments-native-background .region:after,
atom-text-editor::shadow .pigments-native-background-in-selection .region:after,
atom-text-editor .pigments-native-background-in-selection .region:after` => `atom-text-editor.editor .pigments-native-background .region:after,
atom-text-editor .pigments-native-background .region:after,
atom-text-editor.editor .pigments-native-background-in-selection .region:after,
atom-text-editor .pigments-native-background-in-selection .region:after`

* `atom-text-editor::shadow .pigments-native-background-in-selection,
atom-text-editor .pigments-native-background-in-selection` => `atom-text-editor.editor .pigments-native-background-in-selection,
atom-text-editor .pigments-native-background-in-selection`

* `atom-text-editor::shadow .pigments-native-underline .region,
atom-text-editor .pigments-native-underline .region,
atom-text-editor::shadow .pigments-native-underline-in-selection .region,
atom-text-editor .pigments-native-underline-in-selection .region` => `atom-text-editor.editor .pigments-native-underline .region,
atom-text-editor .pigments-native-underline .region,
atom-text-editor.editor .pigments-native-underline-in-selection .region,
atom-text-editor .pigments-native-underline-in-selection .region`

* `atom-text-editor::shadow .pigments-native-underline .region:before,
atom-text-editor .pigments-native-underline .region:before,
atom-text-editor::shadow .pigments-native-underline-in-selection .region:before,
atom-text-editor .pigments-native-underline-in-selection .region:before` => `atom-text-editor.editor .pigments-native-underline .region:before,
atom-text-editor .pigments-native-underline .region:before,
atom-text-editor.editor .pigments-native-underline-in-selection .region:before,
atom-text-editor .pigments-native-underline-in-selection .region:before`

* `atom-text-editor::shadow .pigments-native-underline .region:after,
atom-text-editor .pigments-native-underline .region:after,
atom-text-editor::shadow .pigments-native-underline-in-selection .region:after,
atom-text-editor .pigments-native-underline-in-selection .region:after` => `atom-text-editor.editor .pigments-native-underline .region:after,
atom-text-editor .pigments-native-underline .region:after,
atom-text-editor.editor .pigments-native-underline-in-selection`

**Comment by C-Bouthoorn** [comment]
Related to https://github.com/abe33/atom-pigments/issues/239
