### ISSUE TITLE
Just wanted to say thanks

### ISSUE THREAD

**Issue by cbcoutinho** [abe33/atom-pigments#323]
Howdy @abe33,

Just wanted to say thanks for fixing the number of issues that came up in the last few weeks. I know you received a bunch of online flak, and hope all is well. Keep up the great work, pigments is a great project.

:+1:

**Comment by abe33** [comment]
Hi @cbcoutinho, thank you for the support, I really appreciate it. It's true it have been a tough week, but we all have to live with our own mistakes, and there's still something to learn from that.
