### ISSUE TITLE
[Feature Request] add hex code to color suggest menu

### ISSUE THREAD

**Issue by dhniels** [abe33/atom-pigments#324]
Hope I'm posting this in the right place, but it would be very useful to be able to show a hex code to the right of the little color preview circle (see screenshot):

![screen shot 2017-08-03 at 1 33 12 pm](https://user-images.githubusercontent.com/7034022/28940614-83842cb8-7852-11e7-960d-9bcab6569193.png)

**Comment by abe33** [comment]
Actually it's already provided using the [Extend Autocomplete To Color Value](https://github.com/abe33/atom-pigments#extend-autocomplete-to-color-value) setting. True, the naming is quite poor, I found myself taking some time to find which setting it was.

**Comment by dhniels** [comment]
@abe33 awesome, thank you. how exactly do i enable it? i see its set to false but couldn't find where it said how to set it to true...

**Comment by C-Bouthoorn** [comment]
Go to Atom > Settings > Packages > search for Pigments > Scroll down a little, and search for "Extend Autocomplete To Color Value". It should be the second one of the three grouped ones.
