### ISSUE TITLE
I can somehow see two layers of the highlighted text

### ISSUE THREAD

**Issue by stevemao** [abe33/atom-pigments#33]
![screen shot 2015-06-18 at 4 39 04 pm](https://cloud.githubusercontent.com/assets/6316590/8225484/a9a96784-15d8-11e5-9efe-5a428fa69988.png)

The overlapped highlight is a bit high for some reason so you can see the original text below it.

**Comment by abe33** [comment]
Thanks for the report, a patch will come today with a fix for that.

**Comment by stevemao** [comment]
Thanks for fixing it so quickly :D
