### ISSUE TITLE
pigments does not work in stylesheet inside html file

### ISSUE THREAD

**Issue by sbecerek** [abe33/atom-pigments#332]
Color dots do not show in the stylesheet inside HTML files when I make the font size anything bigger than 11px, but works perfectly inside CSS files.

**Comment by C-Bouthoorn** [comment]
Would you mind sharing your Atom version, Pigments version, and OS? 😄

**Comment by suheybbecerek** [comment]
pigments version 0.40.2 atom version 1.19.0 thanks for helping and sorry for late response
