### ISSUE TITLE
Pigments doesn't detect, toggle or trigger the colours in Atom Beta 1.20

### ISSUE THREAD

**Issue by gusbemacbe** [abe33/atom-pigments#339]
Hello,

### Versions 
```
Atom Beta 1.20.0 Beta 4
Chrome 56.0.2924.87
Electron 1.6.9
Node 7.4.0

apm 1.18.4
git 2.13.3
npm 3.10.10
node 6.9.5 x64
python 2.7.13.
```

I use Atom Material as UI theme and Atom Burnt Orange or Material Palenight as syntax themes.

### Enabled packages:
```
Atom Beautify
Color Picker
FiraCode
Fonts (monospaced fonts)
Sort Selected Elements
```

### Pigments config:
```
autocompleteSuggestionsFromValue: true
extendAutocompleteToColorValue: true
extendAutocompleteToVariables: true
groupPaletteColors: "by file"
markerType: "gutter"
mergeColorDuplicates: false
sortPaletteColors: "by name"
```

I use CSS

Here is the screenshot, as you can see the colours are not highlighted in the gutter:
![screen shot 2017-08-23 at 02 58 50](https://user-images.githubusercontent.com/2257024/29600916-0f7dc920-87af-11e7-876a-219e1927fbf2.png)

But it strangely did work on LESS:

![screen shot 2017-08-23 at 03 03 46](https://user-images.githubusercontent.com/2257024/29601050-d80c3386-87af-11e7-9709-100a85452410.png)

**Comment by C-Bouthoorn** [comment]
I see you've closed the issue. Did you do anything specific to solve it, or did it just so happen to solve itself?

**Comment by gusbemacbe** [comment]
My topic is 2 years old. It seemed that it is no longer solved. Pigments stopped of working on the last version of Atom on Manjaro Linux and I migrated to another text editor. I use Atom only to replace, using the Regex and convert the colours, using Pigments, but now Pigments is not working here.

**Comment by C-Bouthoorn** [comment]
I see. Thanks for your response, I'll keep the issue closed

**Comment by gusbemacbe** [comment]
It seems that I solved it, because Pigments missed the CSS files, I added `.css`, and `.source.css`.
