### ISSUE TITLE
OS stops when atom in launching

### ISSUE THREAD

**Issue by MerDenchik** [abe33/atom-pigments#340]
When I have pigments 0.40.0 or higher, OS freezes and I can't do anything. I should reload PC only but the problem still remains. If I remove pigments, the problem disappears. If I install v0.39.1, the first problem is absent, but I get issues and Pigments isn't working.

OS: Elementary OS Loki x64
Atom: v1.19.2

Please fix it, I really need this plugin.

**Comment by ahallicks** [comment]
I have the same as above on files with a number of colour variables.

My project is broken down into modules and each module (bunch of SCSS files) has a variables file that handles all of the changeables.

These files have about 200 lines and a load of colour definitions. When the file loads and pigments is applied the file stops responding. Then Atom stops responding. Then a couple of seconds later the OS completely freezes. I tried waiting half an hour but still nothing so have had to restart.

**Comment by WolfieMario** [comment]
Reproduced consistently three times on Windows 10. After I deleted the package, the freezes stopped.

For the last freeze, I ran Task Manager and watched while launching Atom. Normally, for my two Atom windows, there are eight Atom processes running. However, when I launched with pigments installed, the Task Manager window rapidly filled up with Atom instances.

I was unable to check exactly how many instances were running, as the header with the count was scrolled off-screen, and it froze immediately afterwards. It was definitely at least 25 instances; I wouldn't be surprised if it actually numbered in the hundreds.

**Comment by phun-ky** [comment]
I get a somewhat similar result with pigments. I am on ubuntu 16.04 and when alt+tabbing back to atom, it freezes from time to time, and on about 1out of 10 freezes, the OS freezes and I have to restart x

**Comment by ChrisCinelli** [comment]
Same problems here. Reported https://github.com/atom/atom/issues/15684
Pigments is the problem.

Before everything dies I see a ton of Atom Helper process being created.

**Comment by C-Bouthoorn** [comment]
Closing in favour of the [master post](https://github.com/abe33/atom-pigments/issues/351).
