### ISSUE TITLE
Cannot find 'highlights-component' in the require cache.

### ISSUE THREAD

**Issue by amarin1990** [abe33/atom-pigments#341]

**Comment by C-Bouthoorn** [comment]
Duplicate of https://github.com/abe33/atom-pigments/issues/335 https://github.com/abe33/atom-pigments/issues/334 https://github.com/abe33/atom-pigments/issues/329 https://github.com/abe33/atom-pigments/issues/328 https://github.com/abe33/atom-pigments/issues/318 https://github.com/abe33/atom-pigments/issues/314 https://github.com/abe33/atom-pigments/issues/201 https://github.com/abe33/atom-pigments/issues/338
