### ISSUE TITLE
native-dot, native-square-dot, and gutter display options not functioning

### ISSUE THREAD

**Issue by Zachcos** [abe33/atom-pigments#342]
While starting a new project today, I realized pigments had reset my display setting to `background`

I switched this to my preferred option, native-dot, and nothing displays. Same case with `native-square-dot` and `gutter`.

If I switch back to any other display option (`background`, `underline`, `outline`) it works correctly.

Anyone else having this issue?
```
Atom v1.19.4
Pigments v0.40.2
```

**Comment by jj-carlson** [comment]
Yes, also running into the issue. Developer tools says the following:
`Error setting item in object: Validation failed at pigments.markerType, "dot" is not one of ["native-background","native-underline","native-outline","native-dot","native-square-dot","gutter"]
coerce @ <embedded>:21343
`

**Comment by samc449** [comment]
I have the same issue, also the Pigments option in the right click menu no longer appears so I can't convert hex to rgba as an example.

**Comment by IiroP** [comment]
I had that issue, but disabling and re-enabling the extension fixed it.

**Comment by jj-carlson** [comment]
@IiroP Ah, yes, nothing complicated. Thank you!

**Comment by Zachcos** [comment]
Disabling and re-enabling the plugin doesn't have the same effect for me... still have no-show markers after disabling/re-enabling.

**Comment by irvingv8** [comment]
Running into this issue, disabling and re-enable didn't work for me either. Also tried reinstalling the package with no effects.

**Comment by chrismadrigal** [comment]
Any updates here? Having the same issue

**Comment by vincent-ML** [comment]
I have the same error

**Comment by Mayccoll** [comment]
Same error just work ```native-background``` and right click menu no longer appears
Atom 1.24.0
Linux Mint
Pigments 0.40.2

**Comment by nlound** [comment]
Same Here:
OS: Sierra 10.3.4
Atom: 1.26.1 (fresh install)
Pigments 0.40.2 (fresh install)
Any color theme.

**Comment by krzmaciek** [comment]
Have the same issue :/
Atom    : 1.29.0
Pigments: 0.40.2
