### ISSUE TITLE
Marker types not working

### ISSUE THREAD

**Issue by Bandi017** [abe33/atom-pigments#343]
after updating Atom to 1.19.4 and also updating the package the markers: native-dot, native-square-dot and gutter are not working anymore. Native-background, native-underline, native-outline are working though.

**Comment by C-Bouthoorn** [comment]
Could you please state your OS and Pigments version as well?

**Comment by C-Bouthoorn** [comment]
Duplicate of https://github.com/abe33/atom-pigments/issues/342
