### ISSUE TITLE
Color dot & dot-square not vertically aligning with line-height and font-size 

### ISSUE THREAD

**Issue by matthewfarlymn** [abe33/atom-pigments#35]
![screen shot 2015-06-18 at 11 50 24 am](https://cloud.githubusercontent.com/assets/5617870/8235486/469431ec-15b0-11e5-8642-530337a08502.png)

**Comment by abe33** [comment]
The positioning issue is fixed but I still haven't found a good solution to detect the setting changes to update the markers, in the config change callback the editor's line height is still the previous one, and all the measuring happens in the react component and the presenter, but there's no event I can use without killing the performance here.

**Comment by matthewfarlymn** [comment]
Excellent, looks great!
