### ISSUE TITLE
Feature Request: Gradients

### ISSUE THREAD

**Issue by mike3run** [abe33/atom-pigments#352]
I don't know how hard can be to implement but given that nowadays designers are loving to use gradients it'd be nice to have some sort of way to store them as variables and actually see the result somewhere else.
<img width="508" alt="screen shot 2017-09-25 at 9 03 02 am" src="https://user-images.githubusercontent.com/7088511/30812472-696bbbe6-a1d0-11e7-9c65-f75cbb2fd654.png">

So maybe for example the bottom variant could be shown like the rendered gradient? covering the whole `linear-gradient(#ff2d91, #ff643c)` part?

**Comment by C-Bouthoorn** [comment]
Not sure how and if gradients are supported in this case.
How would you represent them in the gutter or underlined?

**Comment by mike3run** [comment]
in the gutter i can see them as the tiny circles they are already but with the gradients.

the proposal in the editor view is that all of the:

`linear-gradient(#ff2d91, #ff643c)` string gets the color, if that makes sense?

I know my way around JS, not so much around coffeescript but with a quick overview from you i'll be glad to figure this out on my following weekends

**Comment by mike3run** [comment]
<img width="549" alt="screen shot 2017-09-25 at 4 54 49 pm" src="https://user-images.githubusercontent.com/7088511/30832861-5f7c8696-a212-11e7-980a-0470d585a97e.png">

After a quick and dirty dive in the inspector in atom i think this would be the ideal outcome at least just for word highlighting.

I saw you're already using gradients albeit in the same color so that hopefully means some of the work is already done (?)

**Comment by mike3run** [comment]
I think that can work with all the other options as well 😄  what do you think @C-Bouthoorn

**Comment by C-Bouthoorn** [comment]
Looks okay to me! Could you use the code from your screenshot to issue a PR?
