### ISSUE TITLE
Add support for 4 and 8 digit hex colors

### ISSUE THREAD

**Issue by awayken** [abe33/atom-pigments#36]
Future specs of CSS include 4 and 8 digit hexadecimal colors where the final value is an alpha channel. The CSS Color Module 4 has more information: http://dev.w3.org/csswg/css-color/#hex-notation

For instance, `#0000ffcc` and `#00fc` would be equivalent to `rgba(0, 0, 100%, 80%)`.

**Comment by abe33** [comment]
Oh cool, I didn't know it was in the csswg pipe. It'll be really easy to add so an update should land soon.
