### ISSUE TITLE
pigments is too slow to freeze the main thread

### ISSUE THREAD

**Issue by llqgit** [abe33/atom-pigments#360]
![warning in atom console](https://user-images.githubusercontent.com/8063914/31871016-d7e8a0ce-b7e3-11e7-8cd6-b30f6131d74b.png)

It has locked my main thread for 21 more seconds. I still don't know why and what's caused it

**Comment by C-Bouthoorn** [comment]
Please see https://github.com/abe33/atom-pigments/issues/351
