### ISSUE TITLE
Open multiple files in CLI freeze atom

### ISSUE THREAD

**Issue by PapsOu** [abe33/atom-pigments#363]
Related to this issue https://github.com/atom/atom/issues/16120 , I've found that the package pigments cause atom to freeze when trying to open multiple files from CLI.

Please follow theses step to reproduce the bug :

```
FILES="";

for i in $(seq 1 15)
do
    echo "File #$i" > "file_$i.txt";
    FILES="${FILES} file_${i}.txt";
done

echo "atom${FILES}"
```

Execute the following command :
```
atom file_1.txt file_2.txt file_3.txt file_4.txt file_5.txt file_6.txt file_7.txt file_8.txt file_9.txt file_10.txt file_11.txt file_12.txt file_13.txt file_14.txt file_15.txt
```

When disabling pigment package, the 15 files successfully opens without freezing atom. When enabling this package, atom freeze, and the OS (Ubuntu 16.04) freeze too (the mouse cursor move very slowly)

**Comment by Janghou** [comment]
Confirmed!

After update to atom 1.22, opening my project failed. Different Atom processes (20+ and 5% memory each) took all my memory (8GB) and freezed Ubuntu for minutes. I was barely able to open another terminal and pkill atom. Disabling pigments package solved the issue.

**Comment by Songworks** [comment]
Been having same/similar issue. Whenever I open multiple files at once (through the tree-view), Atom processes use an excessive amount of memory for a few seconds until it normalizes again. With only 8gb of ram this usually freezes my system while it desperately tries to swap...

Does not happen with pigments disabled.

Unless someone else does it before then, I will do a test in a few days from now with a fresh Atom profile and only pigments installed. Will see if perhaps pigments and another community package together cause this issue.

Atom version: 1.22 (also on 1.21)
System: Linux Mint 17.3 (based on Ubuntu 14.04)

**Comment by federicogodan** [comment]
same problem here

**Comment by kikoseijo** [comment]
Big CSS files crashes also.
Needs a loot at. I had to uninstalling.

**Comment by C-Bouthoorn** [comment]
Please see the masterpost: https://github.com/abe33/atom-pigments/issues/351 You are certainly not the only ones that experience huge amounts of lag and/or crashes
