### ISSUE TITLE
Certain marker types slowing down Atom

### ISSUE THREAD

**Issue by ryanlloydfrench** [abe33/atom-pigments#366]
I have found the following issue: 

When the marker type is set to either 'native-dot' or 'native-square-dot'. Atom chugs on larger files with inline css. Currently working with email templates and it seems to be atom-pigments that is causing Atom to slow right down.

When I set the marker type to 'native-background', performance is smooth again.

Hope this helps out a bit, just want to document the issue.

Pigments Version: 0.40.2
Atom Version: 1.22.1
OS: macOS 10.13.1

**Comment by C-Bouthoorn** [comment]
Please see [the masterpost about this issue](https://github.com/abe33/atom-pigments/issues/351)
