### ISSUE TITLE
Limit this plugin only to files that actually make sense

### ISSUE THREAD

**Issue by alexandernst** [abe33/atom-pigments#372]
Please turn off this plugin when detected a language that just can't use CSS colours, aka, C for example. (writing memory addresses or hex values triggers this plugin)

**Comment by C-Bouthoorn** [comment]
Wait, pigments shouldn't be enabled by default for those files. The default scopes are `.source.css, .source.css.less, .source.sass, .source.css.scss, .source.stylus`. You can check these in Settings > Pigments.
