### ISSUE TITLE
Dot markers stop displaying after line 39

### ISSUE THREAD

**Issue by AntonioDePau** [abe33/atom-pigments#376]
OS:		**Win10 x64**
Atom:	**1.23.2**
Pigments:	**0.40.2**
Themes:	"atom-dark-ui" & "atom-dark-syntax"

Underline, Dot, Square Dot and Gutter do not display after line 39 (font-size 17, line 40 for font-size 16).
Background and Outline markers are working fine.

I tried disabling and reinstalling Pigments, with no results...

![atom-pigments](https://user-images.githubusercontent.com/23122727/34572848-59460a16-f16a-11e7-801b-36ea973ae395.png)

PS: Multiple color tags in CSS added for testing purpose, so you can witness the issue more easily.

**Comment by C-Bouthoorn** [comment]
Seems to be similar to https://github.com/abe33/atom-pigments/issues/333

**Comment by AntonioDePau** [comment]
Temporary solution provided by Mootly [Here](https://github.com/abe33/atom-pigments/issues/333#issuecomment-336317812) worked for me!

Anyone else with this issue, try:

1. Open pigments.less in packages\pigments\styles\
2. Go to line 27
3. Remove/comment "background-attachment: fixed;"
4. (Re)start Atom
