### ISSUE TITLE
Support %23 as replacement for #

### ISSUE THREAD

**Issue by jacobp100** [abe33/atom-pigments#379]
When writing inline SVGs for CSS, you have to replace `#`s with `%23`.

```css
  background: url('data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 12 4"><g fill="%23d4dcde"><circle cx="1.5" cy="1.5" r="1.5" /><circle cx="6" cy="1.5" r="1.5" /><circle cx="10.5" cy="1.5" r="1.5" /></g></svg>')
    center / 12px no-repeat;
```

It would be cool if these were highlighted too!

**Comment by C-Bouthoorn** [comment]
Just a side-note: I would put that SVG in a seperate file, and link to that file in your CSS. I would never inline SVG in a CSS file

**Comment by missmatsuko** [comment]
Also if you care about IE support, you probably need to base-64 encode the SVG:
https://stackoverflow.com/a/21626701
