### ISSUE TITLE
Problems with markers

### ISSUE THREAD

**Issue by gperdomor** [abe33/atom-pigments#380]
Only `native background` and `native outline` works...

<img width="823" alt="screen shot 2018-02-01 at 11 51 50 pm" src="https://user-images.githubusercontent.com/371939/35714358-f30afebc-07aa-11e8-88b8-b682cbb3f291.png">

Im using atom-ide-ui

**Comment by C-Bouthoorn** [comment]
Seems to be a duplicate of https://github.com/abe33/atom-pigments/issues/347. Closing

**Comment by hossamyehia** [comment]
try to write this in atom stylesheet it works with me 

atom-text-editor .gutter[gutter-name="pigments-native-dot"] .pigments-gutter-marker div span,
atom-text-editor .gutter[gutter-name="pigments-native-square-dot"] .pigments-gutter-marker div span,
atom-text-editor .gutter[gutter-name="pigments-native-dot"] .pigments-gutter-marker-in-selection div span,
atom-text-editor .gutter[gutter-name="pigments-native-square-dot"] .pigments-gutter-marker-in-selection div span{
  background-attachment: inherit;
  
}
