### ISSUE TITLE
marker-type native dot not working

### ISSUE THREAD

**Issue by nile54218** [abe33/atom-pigments#383]
atom version 1.24.0

**Comment by waiyan13** [comment]
Restarting the editor or reloading the window doesn't help. Also native square dots doesn't work.
But it works on same color values in other code blocks. I have attached the screenshot below.
![capture](https://user-images.githubusercontent.com/7028708/36933005-38ac838e-1f00-11e8-9523-551b777449f1.PNG)

**Comment by monsterkodi** [comment]
three of the marker types are broken:
- native-dot
- native-square-dot
- gutter

they only show in the top part of the buffer when the parsing is done (first bunch of lines that fits into the editor view)

i hope this clarification might help when hunting the bug down.

**Comment by C-Bouthoorn** [comment]
Duplicate of https://github.com/abe33/atom-pigments/issues/347 and https://github.com/abe33/atom-pigments/issues/342

**Comment by hossamyehia** [comment]
try to write this in atom stylesheet it works with me

atom-text-editor .gutter[gutter-name="pigments-native-dot"] .pigments-gutter-marker div span,
atom-text-editor .gutter[gutter-name="pigments-native-square-dot"] .pigments-gutter-marker div span,
atom-text-editor .gutter[gutter-name="pigments-native-dot"] .pigments-gutter-marker-in-selection div span,
atom-text-editor .gutter[gutter-name="pigments-native-square-dot"] .pigments-gutter-marker-in-selection div span{
background-attachment: inherit;

}

**Comment by C-Bouthoorn** [comment]
Thanks @hossamyehia. I've made a PR of your code (#434) so others can test it.
