### ISSUE TITLE
Pigments incorrectly highlights numeric XML entities in XML and HTML.

### ISSUE THREAD

**Issue by madrussa** [abe33/atom-pigments#39]
Pigments is highlighting XML entities in XML and HTML files:
```
<root>&#160;</root> 
```
the #160 part is being coloured green, when this isn't a colour definition.

Solution, don't highlight #[0-9] values proceeding with a & and ending in ; 
Might be worth also checking for &amp;amp;#160; when the entities are encoded.

**Comment by abe33** [comment]
Yes, this is a real problem with javascipt regular expression. The lack of lookbehind captures makes it almost impossible to match something except when preceded by some expression. I somehow found a way to deal with that kind of things when searching variables names, I'll have to update the other color expressions to fix that. 

Stay tuned.
