### ISSUE TITLE
8-digit hex colors are displayed incorrectly in HTML files

### ISSUE THREAD

**Issue by skwerlman** [abe33/atom-pigments#391]
8-digit hex codes are interpreted as being AARRGGBB in HTML files, even inside of `<style>` tags:

![2018-04-01-094215_491x466_scrot](https://user-images.githubusercontent.com/6954107/38173701-fd2c83a2-3590-11e8-9384-05825d537ba5.png)

They display correctly inside CSS files, though:
![2018-04-01-094315_210x150_scrot](https://user-images.githubusercontent.com/6954107/38173725-1e31e182-3591-11e8-80f7-6d833d059333.png)

**Comment by seandellis** [comment]
8-digit hex codes are also interpreted incorrectly within JSON files.

![screenshot 2018-05-30 11 02 45](https://user-images.githubusercontent.com/1584916/40732540-244c8a5e-63f9-11e8-9ceb-dae3a06b798b.png)

**Comment by C-Bouthoorn** [comment]
I suggest trying to add `html` (and/or `json`) to the array on this line: https://github.com/abe33/atom-pigments/blob/055886d1c7c3a7fe8b3ce010e0e6289572aa62b7/lib/color-expressions.coffee#L35

Let me know if that works, so I can merge that to master

**Comment by seandellis** [comment]
@C-Bouthoorn Thanks for the help! That works perfectly as long as the file extension is .json or one of the others in that array.

![screenshot 2018-06-04 15 12 00](https://user-images.githubusercontent.com/1584916/40939225-abc93b08-6809-11e8-81eb-ddd30cf061cb.png)

Just to note, it will only work based on the file extension. It does not display color based on the selected file syntax in the bottom right corner.

**Comment by C-Bouthoorn** [comment]
Yeah, Pigments bases its layout only on the file extension. It's probably possible to change that, but it'll take quite some refactoring I'm afraid. If someone's up for a challenge, feel free to try it, and I'll be happy to merge it :wink:  For the meantime, I'll add those two extensions to master
