### ISSUE TITLE
Causing lag after latest atom update

### ISSUE THREAD

**Issue by og2236** [abe33/atom-pigments#394]
Hi,

Atom started lagging behind on keystrokes after the latest update. After disabling all packages I started to test each one on its own and pigments was the culprit.

**Comment by WiliTest** [comment]
In my case, I had to uninstall it because it crashed atom which completely froze windows (I had to reboot windows several times)

**Comment by C-Bouthoorn** [comment]
Duplicate of https://github.com/abe33/atom-pigments/issues/351
