### ISSUE TITLE
when i install pigment in my atom editor- editor not responding 

### ISSUE THREAD

**Issue by Sujeetdihuli** [abe33/atom-pigments#397]

**Comment by Kivylius** [comment]
same here complete crash atom and even my pc (mac) on latest version of everything.

**Comment by GaetanQucit** [comment]
Ran into the same problem !

**Comment by C-Bouthoorn** [comment]
Duplicate of https://github.com/abe33/atom-pigments/issues/351

@GaetanQucit Try clearing your apm cache and installing again, it seems the files are corrupted
