### ISSUE TITLE
Huge memory consumption (actually huge)

### ISSUE THREAD

**Issue by branditodesign** [abe33/atom-pigments#398]
I had just installed the pigments package and it choked my entire computer, using 10GB+ of RAM and upon restarting the computer and starting Atom up, it used 12GB+ of RAM! Disabling this package (pigments 0.40.2) has fixed this for me although this cannot be normal, I have never seen an applications memory usage in the tens of thousands of megabytes before...

I have 3D games that use half of that...

**Comment by C-Bouthoorn** [comment]
Duplicate of https://github.com/abe33/atom-pigments/issues/351
