### ISSUE TITLE
variables that aren't colors in find colors

### ISSUE THREAD

**Issue by braver** [abe33/atom-pigments#4]
highlighting in files is improved, but there are still a lot of hits in the find results that shouldn't be there.

![screen shot 2015-04-23 at 14 25 21](https://cloud.githubusercontent.com/assets/2543659/7297004/01cea63a-e9c5-11e4-8669-3710fb125447.png)

**Comment by abe33** [comment]
Yes I had noticed that too when running the search in isotope, I have an idea of the problem origin so it should be fixed quickly, I just have to find how to reproduce that in the tests so that I can make sure it doesn't break later.

Anyway, thanks for all the feedback, that's really helpful!

**Comment by abe33** [comment]
Fixed in 0.1.4
