### ISSUE TITLE
System is lagging and crash

### ISSUE THREAD

**Issue by iliyaZelenko** [abe33/atom-pigments#401]
Hi, after installing on windows 10 my system start lagging so much and after a few seconds everything stopped, i restart computer and run atom again - same effect, i have vue and [stylus file](https://i.imgur.com/ldPUL08.png?1). After uninstalling everything worked.  
Atom    : 1.27.2
Electron: 1.7.15
Chrome  : 58.0.3029.110
Node    : 7.9.0

**Comment by C-Bouthoorn** [comment]
See https://github.com/abe33/atom-pigments/issues/351
