### ISSUE TITLE
hsl not working

### ISSUE THREAD

**Issue by paulequilibrio** [abe33/atom-pigments#404]
Hi, thanks for that amazing package.
But, unfortunately, I can't get hsl pigments on js files. It's working: hex, rgb, hsla, but not hsl:
```
hsla(60,100%,50%,1); => working
hsl(60,100%,50%); => not working
```
I'm using Linux, Atom v1.28.0 and pigments v0.40.2.

Thanks in advance!

**Comment by C-Bouthoorn** [comment]
Please try this fix: https://github.com/abe33/atom-pigments/pull/405

**Comment by paulequilibrio** [comment]
Thanks, it worked.

**Comment by chrisdrackett** [comment]
@C-Bouthoorn is this working in all file types? I'm in a json file using the master branch of this project from GitHub and it seem to only pick up `hsla` and not `hsl`

![example](https://cl.ly/6c468a597bde/Screen%20Shot%202019-03-19%20at%202.37.16%20PM.png)
