### ISSUE TITLE
Dots are displaying in middle of code

### ISSUE THREAD

**Issue by THRILLHOUS** [abe33/atom-pigments#407]
<img width="512" alt="image" src="https://user-images.githubusercontent.com/24922995/44373781-ccf28000-a49f-11e8-89a2-79bacec70ca9.png">

**Comment by C-Bouthoorn** [comment]
Ehm, I believe you uploaded the wrong picture

**Comment by THRILLHOUS** [comment]
Hi Charlie,

Sorry about that. 

I deleted the package and reinstalled and it ended up placing the dots at the end of each line. So we’re good. The picture I was trying to upload had the pigment dots about four spaces in at the beginning of the line, overlapping code.

Thanks for getting back to me.

**Comment by C-Bouthoorn** [comment]
Nice to know it has been fixed. Closing this issue.
