### ISSUE TITLE
Incorrect highlight for ruby hash

### ISSUE THREAD

**Issue by tsl0922** [abe33/atom-pigments#41]
![image](https://cloud.githubusercontent.com/assets/1680515/8323273/a4993dfa-1a74-11e5-88b6-aa0b58d83782.png)

There is no color here, but it is highlighted.

**Comment by abe33** [comment]
Thanks for the report, It's mostly the same problem as in #39. Lookbehind captures not being available in JS make this kind of thing really hard to not catch with basic regexp.
