### ISSUE TITLE
pigments causes atom to stop responding

### ISSUE THREAD

**Issue by TristanBrotherton** [abe33/atom-pigments#43]
With atom 1.0 and pigments installed the editor will stop responding after about 7 seconds. It is initially showing color previews as expected.
What can i do to provide you with more useful information?

**Comment by abe33** [comment]
Hmm, maybe you can start by telling me about the conditions in which it occurs? 
Like, is it systematic? 
Does it occurs only for some projects? If it's only on some projects, how big are these projects? 
Is there a lot of directories and files?

**Comment by TristanBrotherton** [comment]
Hi Cedric, 

This is a sizeable project, we have 658 less files, but a considerable amount of those should be excluded as per the settings in pigments. 

If I start Atom without this project, pigments will run. 

What is odd is pigments seems to run fine for 7(ish) seconds and then Atom will become un-responsive. Disabling pigments resolves the issue.

Thanks, Tristan

**Comment by abe33** [comment]
Thanks for the quick reply, maybe there's a problem at some point when scanning the files content, I'm at codeconf actually, so I'll try to make a biggest reply later with instructions so that we can narrow down the issue.

**Comment by TristanBrotherton** [comment]
Thanks! Your work with this is very much appreciated. There is no other LESS color parser!

**Comment by TristanBrotherton** [comment]
@abe33 I was able to resolve this issue.
In our project we had LESS files that had non LESS logic in them to insert dynamic variables from our DB. Pigments was attempting to parse these and failing. Adding the files to the ignored glob, resolved the issue.

If you'd like further details on the structure that was causing it to hang, just let me know.

**Comment by abe33** [comment]
Oh great! Yes, I'm interested in the structure, if I can fix the scanning issue it's even better, isn't it?

**Comment by TristanBrotherton** [comment]
Here is an example of our marked up LESS file that runs through a Django processor before being used. It will cause Pigments to barf. In an ideal world pigments would just ignore it. 

```
@myVarName: {{ django_var }};

.regularLessClass {
 color: @myVarName;
}

{% if something %}
@import "something.less";
{% endif %}

```

**Comment by abe33** [comment]
Thank you @TristanBrotherton, I'll add a test for that case as well.

**Comment by abe33** [comment]
Hi @TristanBrotherton, I tried the snippet you provided me and I fail reproducing the freeze. Was there something beyond the fact of using injected variables?

**Comment by TristanBrotherton** [comment]
@abe33 I sent you an email.

**Comment by abe33** [comment]
Ok thanks! I'll take a look asap

**Comment by simpsondigital** [comment]
Hi there. I seem to be having a similar issue with Pigments. Also a large project with a lot of template dependencies which include a good number of scss files. I also experience Pigments working for a short period, then total lock-up. Any additional info I can provide?

**Comment by abe33** [comment]
@simpsondigital Ideally, if you could provide reproduction steps I could investigate it myself, or information about the project structure that triggers that lock-up, as well as the pigments configuration you're using.

**Comment by juanfernandoe** [comment]
+1

**Comment by ctcpip** [comment]
https://github.com/abe33/atom-pigments/issues/125#issuecomment-301616296

**Comment by ctcpip** [comment]
see my comment here - I think it may be related or the same issue

https://github.com/abe33/atom-pigments/issues/125#issuecomment-301616296

**Comment by C-Bouthoorn** [comment]
Closing in favour of the [master post](https://github.com/abe33/atom-pigments/issues/351).
