### ISSUE TITLE
Installing Pigment is crashing my Atom and not working

### ISSUE THREAD

**Issue by JordanMHebert** [abe33/atom-pigments#430]
I have tried four different times to install the pigment package, and each time it will show installing for a few seconds and then it keeps crashing my Atom. Every time it then proceeds to kicks me out, and I have to go back in again. When I go back in, I have noticed each time it will show pigment installed under my packages, but it does not work. As I have then proceeded each time to go to the CSS document, I am working on, and when I type in the color, I want the name of the color is there, but the background does not change to that color. Could you please help? Thank you!

**Comment by BlueskyFR** [comment]
@JordanMHebert I am having the same problem too!
Pigments made me hard reset around 10 times my PC by making Atom crash!

**Comment by C-Bouthoorn** [comment]
I'm afraid I'll have to forward you to the master post about this: #351 You're certainly not the only one with issues, but it's really hard to reproduce and/or fix. At this point, it seems I'm the only contributor and I can't reproduce this locally, so it would be perfect if either of you were able to give sample files and/or CPU profiles and/or more information on how to fix this.
