### ISSUE TITLE
 Infinite loading

### ISSUE THREAD

**Issue by Mr2803** [abe33/atom-pigments#432]
From the first moment I installed pigments I noticed that any operation I did on atom I get the wheel of loading windows. I state that I have a recent computer with ryzen 5 3600x, 16gb ram so I would exclude that this is a problem with my machine, but I hypothesize that it is instead a compatibility problem with the 3000 series of ryzen. It's a shame because I loved pigments, but that little wheel gets on my nerves. Has anyone encountered a similar problem?

**Comment by C-Bouthoorn** [comment]
I'm afraid I'll have to forward you to the master post about this: #351 You're certainly not the only one with issues, but it's really hard to reproduce and/or fix. At this point, it seems I'm the only contributor and I can't reproduce this locally, so it would be perfect if either of you were able to give sample files and/or CPU profiles and/or more information on how to fix this.
