### ISSUE TITLE
the dot is not function

### ISSUE THREAD

**Issue by hong-tm** [abe33/atom-pigments#433]
The dot cannot funtion(dot,square dot)

**Comment by C-Bouthoorn** [comment]
I'm afraid I'll have to forward you to the master post about this: #351 You're certainly not the only one with issues, but it's really hard to reproduce and/or fix. At this point, it seems I'm the only contributor and I can't reproduce this locally, so it would be perfect if either of you were able to give sample files and/or CPU profiles and/or more information on how to fix this.

**Comment by hong-tm** [comment]
ok, thanks for respond, i will send you the picture as soon as possible!

**Comment by hong-tm** [comment]
ideapad 330-15arr
amd ryzen 5 2500u with radeon vega mobile gfx 2.00ghz
radeon 540
window 10 pro, 1809


Charlie Bouthoorn <notifications@github.com> 于 2019年10月7日周一 00:59写道：
