### ISSUE TITLE
General Editor Crash

### ISSUE THREAD

**Issue by Kerubinz** [abe33/atom-pigments#435]
My atom editor keeps on crashing along with the rest of my operating system whenver I try to install the atom-pigments package on my atom. It's too bad for I would very much like to try your package for myself. 

Hoping for a solution soon. Thank you. #435 #198

**Comment by C-Bouthoorn** [comment]
Hej, I'm sorry to tell you that this is a known issue, but that we don't know how to resolve it. Could you please elaborate in #351 what system you're using, which version of atom, which files you tried loading, a CPU timeline and/or any other information that could help us fix this?
