### ISSUE TITLE
Error in installing....Plzz Help

### ISSUE THREAD

**Issue by sankupani211** [abe33/atom-pigments#449]
Installing “pigments@0.40.2” failed.Hide output…

npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! Unexpected end of JSON input while parsing near '...s":{"chalk":"^1.1.1",'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\sanku\.atom\.apm\_logs\2020-05-30T14_15_10_036Z-debug.log

**Comment by Cxarli** [comment]
try clearing the cache and downloading again, seems to be a download issue
