### ISSUE TITLE
Sometimes Less variables w/ comments are showing double (& different) color swatches

### ISSUE THREAD

**Issue by dapearce** [abe33/atom-pigments#45]
![screen shot 2015-06-26 at 4 04 23 pm](https://cloud.githubusercontent.com/assets/1824987/8386303/3963ec10-1c1d-11e5-9a2d-4f11dba0bfac.png)

**Comment by abe33** [comment]
Hmm, actually it's because there is the words `Blue`, `Red`, `Yellow`, etc. in the comments, you can ignore colors in comments by setting `\.comment` in the `Ignored Scopes` setting of pigments.
