### ISSUE TITLE
Installing “pigments@0.40.2” failed

### ISSUE THREAD

**Issue by chawlaamal170401** [abe33/atom-pigments#450]
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm ERR! code Z_BUF_ERROR
npm ERR! errno -5
npm ERR! zlib: unexpected end of file

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Amal\.atom\.apm\_logs\2020-06-03T07_05_33_846Z-debug.log

how to fix this?

**Comment by Cxarli** [comment]
seems like a failure during download, try clearing the cache and downloading again, and make sure you have enough disk space and memory left
