### ISSUE TITLE
pigments isn't working

### ISSUE THREAD

**Issue by ghost** [abe33/atom-pigments#477]
I installed pigments from atom settings UI and right off the bat it doesn't work. I tried reinstalling it through the terminal, and had some success there, i.e. whenever I start atom, it works and I can see all of the visual parsings in the associated files, however as soon as I start changing the colors (either by typing or by using the color-picker package), the preview gets disabled for that particular color. Moreover, I tried installing versions 37 and 38 later, but I couldn't even see the initial previews while using these versions.

PS: I tried uninstalling color-picker and then reinstalling pigments but ended up with similar results.

Specs:
macOS Monterey v12.2
Atom v1.59.0
pigments v0.40.6
Electron v9.4.4
Node v16.13.2

Last Notes: I am an entry-level programmer and I might not be knowing a lot about what I am talking here. There might be some solution similar to this situation resolved earlier which I missed, if that's the case then pardon me and be kind enough to point me in the right direction. However, when I tried going through the active issues on this repo, I couldn't find any responses that could work as a fix.

**Comment by Cxarli** [comment]
This is a known long-standing issue already discussed in #351 , so I'll close this issue to avoid duplication. Thanks for bringing it to our attention though :blush:
