### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by cjwelborn** [abe33/atom-pigments#48]
It bubbles up here:
```
/home/cj/.atom/packages/pigments/lib/color-buffer.coffee:211 TypeError: Cannot read property 'name' of undefined
```

I traced it to `lib/variables-collection.coffee:348`:
```coffee
347: for variable in variables
348:   if dependencies = @dependencyGraph[variable.name] # <- `variable` is undefined.
349:     for name in dependencies
350:       if name not in dirtyVariableNames and name not in createdVariableNames
351:         dirtyVariableNames.push(name)
```

I've never used coffeescript, so I'm having to translate this to javascript doing the best I can to track down the original cause. I tried the naive thing and added this:
```
if variable.name? and (dependencies = @dependencyGraph[variable.name])
```

..but that was just a shot in the dark from a coffeescript/atom newb. It didn't help. To be honest I don't know  how or when this code is converted to javascript (would editing the .coffee file have any affect at all after restarting Atom?).

**Comment by abe33** [comment]
Thanks for the report, I think the main issue here is that we should never get a `null` or `undefined` value in the `variables` array. I'll put a guard for now and publish a patch today.
