### ISSUE TITLE
Support for Pulsar?

### ISSUE THREAD

**Issue by SilentGlasses** [abe33/atom-pigments#488]
[Pulsar](https://pulsar-edit.dev/) is the successor of Atom, I can install your package to the platform but it shows no highlights at all.  Can this be looked into?
![Screen Shot 21](https://user-images.githubusercontent.com/22822565/215614722-05748760-606b-4603-a3d6-fa6bb8015571.png)

**Comment by SlyAceZeta** [comment]
Looks like the syntax theme you're using is incompatible with Pigments. I've just installed it and it works fine for me with your code example (using [Threshold](https://github.com/binaryfunt/threshold-ui) for UI and [Convergent](https://github.com/binaryfunt/convergent-syntax) for syntax):

![image](https://github.com/abe33/atom-pigments/assets/11371137/ed840963-8211-47ee-baf8-2bf7b819a14a)

**Comment by SilentGlasses** [comment]
Ah yeah, sorry, forgot to update this.  Not sure what changed but it's not working as expected.
