### ISSUE TITLE
Perfomance issues

### ISSUE THREAD

**Issue by TristanBrotherton** [abe33/atom-pigments#5]
This slows Atom to a crawl. I'd love to give you more 'useful' information if you tell me what I can do.

**Comment by dsandstrom** [comment]
@abe33 I ran a few profiles, hopefully they help: 
Pigments and autocomplete-plus enabled: https://gist.github.com/dsandstrom/f78d8000097427244be0
Pigments and no autocomplete-plus: https://gist.github.com/dsandstrom/a24bd1262bf7b7167623
No pigments: https://gist.github.com/dsandstrom/a13bc517eca0df059802

@TristanBrotherton See https://discuss.atom.io/t/looking-for-testers-for-pigments/16301 for further discussion.  Run a profile as Cedric recommends.

**Comment by dsandstrom** [comment]
I think this is fixed by v2.0.

**Comment by abe33** [comment]
Hi there, sorry to catch up only this late.

As @dsandstrom noticed, v0.2.0 fixes performances problem in the autocomplete provider and in various other spots, but of course there's still room for improvements. As always it's make it works, make it fast.

The provider issue was mainly time spent generating the color palette by filtering the whole variables set, which require evaluating if the variable is a color or not, and with all the variables and operations in a project defining a single color value can be quite costly, so performing over every variables on each keypress was killing it. For the moment I'm just memoizing the palette and invalidate the cache every time a variable change, is added or is removed. I'm planning to review that so even when you've got thousands of variable the cost of updating the color variables list (some variables that couldn't be evaluated become valid, and vice versa), but it'll take me some time to test these approaches.

I'm always interested in details about the project configurations that lead to performances issues as well as profile records of such performances. 
By project configuration I mean how many files in the project and the languages involved (sass, scss, less, stylus, etc.). I'm using it everyday so I found myself in many situations that lead me to detect such issues, but as practices and structures changes a lot depending on the context I can't always anticipate them.

**Comment by abe33** [comment]
I'll close it know, let me know if you still have performances issues.
