### ISSUE TITLE
Pigments don't update their geometry when font-related attributes change

### ISSUE THREAD

**Issue by AlexTuduran** [abe33/atom-pigments#51]
When changing the font family, font size, font height or any other attribute that causes the characters to shift, the pigments overlay do not update their position and size.

**Comment by abe33** [comment]
Hmm, that's actually not true for font size and line height when modified from the settings, but it's true I don't listen to stylesheets changes. It shouldn't be too hard to fix.

**Comment by AlexTuduran** [comment]
Actually I remember I've tested changing font attributes from settings as well just to check if there's a different behavior, but it seems I get the same results. The only way to heal it is to edit the line containing the color declaration, only then the pigments relocate.

**Comment by abe33** [comment]
Are you sure about changing the settings not affecting the markers?

Because as far as I can tell it works, and there's even tests for that: 

![pigments-resize](https://cloud.githubusercontent.com/assets/247140/8671106/aa841a10-2a22-11e5-87e7-10ac01e67e4d.gif)

The tests: 
https://github.com/abe33/atom-pigments/blob/master/spec/color-buffer-element-spec.coffee#L254-L270

**Comment by AlexTuduran** [comment]
I've checked this usecase specifically then and the problem existed, but now it seems the pigments update when changing font attributes from settings, so it seems you're right on this one, my apologies.

**Comment by abe33** [comment]
No pb, there's always some cases I didn't foresee that may not work, but if I've written tests for a given use case I'm generally pretty confident about them working properly. To being cautious I'll also add a listener to the stylesheets changes events in the next release.

**Comment by AlexTuduran** [comment]
Sounds great! Really useful package btw!
