### ISSUE TITLE
Pigments doesn't show color in autocomplete.

### ISSUE THREAD

**Issue by PHELiOX** [abe33/atom-pigments#52]
Atom version 1.0.2

**Comment by abe33** [comment]
Can you give me more information? 
You bet that is part of the basic feature set that is tested and that I also use everyday, so without more details I can't do anything.

**Comment by PHELiOX** [comment]
An example here.
<img width="400" alt="2015-07-14 19 22 14" src="https://cloud.githubusercontent.com/assets/1183568/8672116/bfa56f3a-2a5d-11e5-967d-1b794c261dfb.png">

No color in autocomplete dropdown and no color on variables, colors only displayed on raw values.
No error or exceptions either.

**Comment by abe33** [comment]
And it still gives you no results when you prefix with `@`?

**Comment by PHELiOX** [comment]
<img width="398" alt="2015-07-15 15 58 08" src="https://cloud.githubusercontent.com/assets/1183568/8693531/5ed02094-2b0a-11e5-83e0-2958ea633a4e.png">

Ah.. yes. My bad, I should start with `@`.

**Comment by abe33** [comment]
Does the palette displayed when running `Pigments: Show Palette` command is empty?

**Comment by PHELiOX** [comment]
Yes, no palette displayed when execute `show palette`, `find colors` and `reload`

**Comment by abe33** [comment]
What gives the following in the devtools console: 

```js
project = atom.packages.getLoadedPackage('pigments').mainModule.getProject()

project.getPaths() // > contains all the paths where pigments looks for variables
project.getVariables() // > contains the variables found in the scanning process
```

I guess the variables array will be empty (that's why you don't see anything in the palette or in autocomplete). But if the paths are also empty, then there's probably something with the paths settings configuration (either `sourceNames` or `ignoredNames` has a value that makes the paths ignored).

**Comment by PHELiOX** [comment]
You are right about these variables, they are empty. But my Atom settings are just as downloaded with some plugins. The ignored names are also defaults. 

<img width="535" alt="2015-07-16 00 31 39" src="https://cloud.githubusercontent.com/assets/1183568/8703853/15600ea4-2b52-11e5-8d9b-2406567341e8.png">

**Comment by abe33** [comment]
And do you see your source files in the array returned by `project.getPaths()` in the above sample?

**Comment by PHELiOX** [comment]
Nothing returned by `project.getPath()` either, it's empty.

**Comment by abe33** [comment]
So there's something with your pigments configuration, can you share with me the content of the `config.cson`?

**Comment by PHELiOX** [comment]
Well I took a look at the config file but found nothing unusual.
```cson
"*":
  "exception-reporting":
    userId: "xxxxxxx"
  welcome:
    showOnStartup: false
  "merge-conflicts": {}
  core:
    projectHome: "/Users/test/Documents/Codex"
  editor:
    invisibles: {}
    showIndentGuide: true
    softWrap: true
    lineHeight: 1.8
    fontSize: 13
    autoIndentOnPaste: false
  "color-picker":
    randomColor: false
    uppercaseColorValues: true
  pigments:
    markerType: "dot"
    sortPaletteColors: "by color"
  minimap:
    plugins:
      "git-diff": true
  "git-log": {}
  "git-plus": {}
  "atom-terminal": {}
```

**Comment by abe33** [comment]
Hmm, I'm a bit at loss here, you're using the default configuration, so its either because the files that contains these variables are ignored (which should not occurs given your config) or because they're not part of the project. Can you tell me a bit about the project structure and the naming convention used for these files, maybe I overlooked something in my way of scanning files.

BTW what's your version of pigments?

**Comment by PHELiOX** [comment]
Oh, you mentioned the project structure, does Pigments search the project folder as .gitignore does? I'm working on a part of a coffee-react project, which folder maybe included in the .gitignore file.

**Comment by abe33** [comment]
Yes, if you have the `core.excludeVcsIgnoredPaths` setting enabled (which is the default), it will ignores everything that is listed in the .gitignore file. 
The paths loader is basically the same than when you use the project-wide search, but I'm starting wondering if this really make sense for pigments. 
I also noticed that I don't handle multiple root folders properly. I'll have to work on that.

**Comment by PHELiOX** [comment]
After reopen the files in a separate project folder, pigments works fine.
Perhaps pigments should load all paths when assigned to a project, load current folder when loose files. But save the variables separately for main project and subproject.
Thanks for the patience!
