### ISSUE TITLE
Pigments freezing atom

### ISSUE THREAD

**Issue by chriskennewick** [abe33/atom-pigments#58]
When opening a large, minified (one-line) css file, Pigments is causing atom to become unresponsive for a long period of time. The freeze appears to be a longer for larger files. I am able to produce this when opening bootstrap.min.css

Atom - 1.0.2
Pigments - 0.9.0

**Comment by abe33** [comment]
Hi, thanks for the report, it seems it has to do with the scopes evaluation to determine if a color should be displayed or not, at least that's what I found with the profiler, I have an idea to improve that, I'll try it as soon as I can find some time.

**Comment by abe33** [comment]
Colors should now take longer to appear but without locking the UI until then.
