### ISSUE TITLE
helper process with 100% cpu when specific construct in file

### ISSUE THREAD

**Issue by despairblue** [abe33/atom-pigments#61]
Just to be sure I started with a completely fresh `.atom` folder and only installed `pigments`.

Repro Steps:

1. open a new file
2. enter: `difference(a,)()` into it, or anything that contains that sequence
3. save it and find that in your process list:
```
despair+ 15175  100  8.1 1500948 643384 pts/5  Rl   00:40   0:42 /usr/share/atom/atom --eval require('/usr/share/atom/resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js').setCacheDirectory('/home/despairblue/.atom/compile-cache/coffee'); require('/usr/share/atom/resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js').register(); require('/usr/share/atom/resources/app.asar/node_modules/coffeestack/index.js').setCacheDirectory('/home/despairblue/.atom/compile-cache/coffee/source-maps'); require('/usr/share/atom/resources/app.asar/src/task-bootstrap.js');
```

The process gets killed when it allocates to much memory:
```
Error: FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - process out of memory

    at Socket.<anonymous> (/usr/share/atom/resources/app.asar/src/task.js:94)
    at emitOne (events.js:77)
    at Socket.emit (events.js:166)
    at readableAddChunk (_stream_readable.js:146)
    at Socket.Readable.push (_stream_readable.js:109)
    at Pipe.onread (net.js:517)
```

The annoying part is that the process is restarted whenever the file is edited.

I suppose the above construct throws the parsing logic in an infinite loop.

**Comment by despairblue** [comment]
https://github.com/abe33/atom-pigments/blob/master/lib/utils.coffee#L71 is called with `a,)(`, so the while loop keeps going for ever since https://github.com/abe33/atom-pigments/blob/master/lib/utils.coffee#L57 will always return zero, there is no closing parentheses.

**Comment by despairblue** [comment]
Moving the last paranthesis into the group for all blend mode regexes fixes this, though I just couldn't figure out how theses regexes are created, I got lost [there](https://github.com/abe33/atom-pigments/blob/39fed4bbdd50a4ad6e3e7278f822c5dcef31f6a0/lib/color-expressions.coffee)

`/^difference\(\s*([^"'\n]+\s*,\s*[^"'\n]+)\s*\)$/` :arrow_right:
`/^difference\(\s*([^"'\n]+\s*,\s*[^"'\n\)]+)\s*$/`

**Comment by despairblue** [comment]
ok, got it. I made a PR

**Comment by abe33** [comment]
Hi @despairblue, thanks for having a look at that, I think the main issue is with `findClosingIndex`, I'll try to find a proper fix for this case with a test that don't crash the runner.

**Comment by despairblue** [comment]
:+1:
