### ISSUE TITLE
It will show color if the class name is a color name.

### ISSUE THREAD

**Issue by saarthaksharma** [abe33/atom-pigments#64]
like in this image you can see it is showing green color even when its a class name 
![screen shot 2015-07-28 at 12 45 45 pm](https://cloud.githubusercontent.com/assets/3650216/8925671/3e6783f2-3527-11e5-8f83-73d78766d8c0.png)

**Comment by abe33** [comment]
Sorry for the late replay, have you try to add the corresponding scope in the `Ignored Scopes` setting?
