### ISSUE TITLE
Please consider a way to disable colors based on expression type

### ISSUE THREAD

**Issue by zyklus** [abe33/atom-pigments#67]
I often look at log files (with no extension, so I can't really filter on scope) that have memory addresses and my files look... odd to say the least ;)

![image](https://cloud.githubusercontent.com/assets/320562/9103238/7021af7c-3c2e-11e5-8b4a-150db36e9efb.png)

I personally don't see the point in parsing 6 or 8 digit hex numbers, though I'm sure _someone_ does, so can I suggest an option to disable colors based on how they were parsed?

Either have another "ignore" field in the settings, or possibly just add a class to the added background tag so I can hide it?  `<div class="region background int_hexa_8">`

**Comment by abe33** [comment]
Have you tried using the `text plain` or `null-grammar` scope to match these files? It should work for every files that doesn't have an extension supported by a grammar. 
You could use the following expression in the `Ignored Scopes` to match it: `\.text\.plain\.null-grammar`.
