### ISSUE TITLE
Error path when try to open files in "Find colors" page

### ISSUE THREAD

**Issue by LukeXuan** [abe33/atom-pigments#68]
When I try to open files with a click in pigments find results pane, it open a file with path whose `\` was replaced by `-` , such as `D:-Developer-Projects-xxx-styles-xxx.less`,

Atom version 1.0.4, OS: Windows 7 Ultimate

**Comment by abe33** [comment]
Hi, and thanks for the report.
It looks like the path in the data attribute are stripped of their backslashes, I'll fix that asap
