### ISSUE TITLE
Missing support for some Stylus built-in functions

### ISSUE THREAD

**Issue by billyjanitsch** [abe33/atom-pigments#72]
Based on some testing and a grep of the source, it looks like Pigments is missing support for several of [Stylus's built-in color functions](http://learnboost.github.io/stylus/docs/bifs.html) such as `alpha`, `transparentify` (as opposed to `transparentize`), and `grayscale`. Any chance of adding support for the complete set?

Thanks so much for writing this package!

**Comment by abe33** [comment]
Hi, and thanks for the report, [`grayscale` is supported](https://github.com/abe33/atom-pigments/blob/master/spec/color-parser-spec.coffee#L324-L336) but you're right about `alpha` and `transparentify`. I may missed them the last time I checked, just the time to add the test for that and I'll push a patch.

**Comment by billyjanitsch** [comment]
Thanks! Sorry for the mistake about `grayscale`. Here's a more complete list of example functions that don't seem to be working for me:
- `red(#000, 255)`
- `blue(#000, 255)`
- `green(#000, 255)`
- `alpha(#000, 0.5)`
- `hue(#00c, 90deg)`
- `saturation(#00c, 50%)`
- `lightness(#00c, 80%)`
- `spin(#ff0000, 90deg)`

**Comment by abe33** [comment]
Oh right, I completely missed the fact that `alpha` and the other components functions can also be used to modify a color, I was only thinking about the read case. For `spin` I forgot to include the support for the `deg` unit in the Regexp.

**Comment by billyjanitsch** [comment]
Thanks for the quick fix, and the great package! :)
