### ISSUE TITLE
Pigments crashing any file opened

### ISSUE THREAD

**Issue by simpsondesign** [abe33/atom-pigments#86]
Just tried to give Pigments a whirl, and it's crashing Atom hard for me. Any file (.txt, .html, .j, .scss) opened works a few seconds, but then everything just totally locks up. Running OS X 10.10.5, Atom 1.0.11, w/ Isotope theme.

**Comment by abe33** [comment]
Do you have any crash report to provide? Or information on the context in which it occurs (how big is the project you're trying to open, what are the dependencies, etc.)? With so little information I can't do much to help you.

**Comment by grinsteindavid** [comment]
me too on windows :/

**Comment by robbinhan** [comment]
atom 1.8.0

```
This ColorBuffer is already destroyed
```
![image](https://cloud.githubusercontent.com/assets/241873/16183915/3f9c348c-36ea-11e6-9dcc-208e6880df39.png)


And will be crash when open large file (182K's json file)

Blow file is open large file's cpu profile

[CPU-20160620T132543.zip](https://github.com/abe33/atom-pigments/files/322762/CPU-20160620T132543.zip)

**Comment by abe33** [comment]
@robbinhan It seems you're dealing with the big performance issue described in #188. Can you try with native decorations instead?
