### ISSUE TITLE
Show Palette opens twice the same tab

### ISSUE THREAD

**Issue by feimosi** [abe33/atom-pigments#87]
When using `Pigments: Show Palette` command two the same tabs with colors are opened.

Package version: 0.14.0
Atom 1.0.11

**Comment by abe33** [comment]
Not sure I understand what the problem is. There is only one palette by project, so when trying to open the view second time it'll activate the open view instead. What would you expect?

**Comment by feimosi** [comment]
No, I meant that they open at once with a single command press. Anyway, now I've just noticed that the problem solved itself, so I'm closing the issue.
