### ISSUE TITLE
Poor performance with autocomplete-plus

### ISSUE THREAD

**Issue by buckyoung** [abe33/atom-pigments#9]
Causes Atom to freeze for ~3-5 seconds when autocomplete (https://github.com/atom-community/autocomplete-plus) kicks in.

**Comment by buckyoung** [comment]
Atom version 0.198.0
autocomplete-plus version 2.12.1
pigments version 0.2.0

**Comment by abe33** [comment]
Thanks for the report, can you give more details about the project in which the problem occurs? Is it public?

**Comment by buckyoung** [comment]
Unfortunately, the repo is not public. Its a large web app with several (~40+) (4kb-500kb) scss files. Bootstrap scss files included. 

Ultimately, when I load up Show Palette (~4seconds), there are over 200 colors defined across 10 files.

**Comment by abe33** [comment]
I've just pushed a new version that should improve drastically the overall performances and in particular the autocomplete performances, can you try it and let me know if things improved for you?

**Comment by marvinosswald** [comment]
Having performance Issues too but it doesn't feel connected to autocomplete-plus my typing just has a small but annoying delay ...

**Comment by abe33** [comment]
I believe the latest version should have improved that greatly, I'll close the issue, feel free to open a new one if you still have performance issues.
