### ISSUE TITLE
Your package causes compile-cache to reach 100% cpu for extended periods.

### ISSUE THREAD

**Issue by envygeeks** [abe33/atom-pigments#95]
**_Linux**_: Ubuntu/GNU 14.04 w/ Kernel 3.13
**_Atom Version**_: `atom --version 1.0.19-5f4f6d2`
**_Atom Package**_: `pigments`

**_Atom Install Method**_: Home Directory with App Armor
**_Install Directory**_: ~/.opt/atom
**_Bin Path**_:
- ~/.local/bin/atom -> ~/.opt/atom/bin/atom
- ~/.local/bin/apm  -> ~/.opt/atom/bin/apm

**_Method of Confirmation**_: We disabled all packages and enabled only your package.
**_Method of Discovery**_: We disabled all packages, enabled packages one by one one while opening and closing the file that the addon trips on and discovered that your package is the one that starts consuming 100% cpu.

**_Source of the file causing problems for your software**_:

``` sh
#!/bin/sh
set -e
pid_file=/etc/startup2.d/stdout/supervise/daemons
touch $pid_file
pids=

if [ -d /etc/stdout.d ] && [ "$(ls -A /etc/stdout.d)" ]; then
  for v in /etc/stdout.d/*; do
    tail -qf "$path" 2>/dev/null &
    pid=$!

    echo $pid > $pid_file
    pids=$pids" $pid"
  done
else
  touch /etc/stdout.d/empty
  tail -qf /etc/stdout.d/empty &
  pid=$!

  echo $pid > $pid_file
  pids=$pids" $pid"
fi

wait $pids
```

**Comment by abe33** [comment]
Hi @envygeeks, thanks for the report. It looks like it had to do with the background task running when scanning a buffer. Have you tweaked the package settings? Would you mind sharing your configuration to see if I can find something like a clue about the issue? 

If the issue really comes from the compile-cache then it could be related to the requiring being written in coffee and compiled on the fly by Atom. I haven't dug enough in this to be sure, but that might be a starting point.

**Comment by envygeeks** [comment]
According to my configuration file I've not tweaked any settings: `pigments: {}`.  I honestly don't know if it comes from compile-cache but we assumed it did because it was requiring the compile cache (it could really be something else) but we do have a background process that is launched and consuming the CPU.  The reason we assumed it was the compile cache over it requiring it was because it was the only process that required the cache, all other processes neglect that.

**Comment by abe33** [comment]
I didn't noticed it before, but it seems that recently Atom started to recompile all the files used used in a task whenever the task is started. I'm not sure so I'll have to investigate that.

**Comment by abe33** [comment]
I reviewed the code and found a condition leading to an infinite loop when parsing an expression, I published a patch for this case, let me know if you find some improvements with the new version.

**Comment by C-Bouthoorn** [comment]
Closing in favour of the [master post](https://github.com/abe33/atom-pigments/issues/351).
