### ISSUE TITLE
Color indicator on the gutter

### ISSUE THREAD

**Issue by sanusart** [abe33/atom-pigments#97]
Hi,

I think it could be nice to have the color indicator on the gutter among other options, like in line 17:
![image](https://cloud.githubusercontent.com/assets/267718/10411085/872c08a8-6f63-11e5-80b1-2228dc140bc5.png)

**Comment by abe33** [comment]
Hi @sanusart, thanks for the suggestions. 
I think it was requested once a long time ago but at that time there was no API to create custom gutters and such. 

However, it's not as trivial as it seems, one issue is that pigments currently doesn't use Atom's decorations API, as it's not possible to pass custom content/attributes to the decorations (which is needed here to specify the color and to set the marker text in the case of background markers). It would require some refactoring to switch between the current custom marker behaviour and the gutter one. 
The other issue I see is when there's several markers on the same line (in a linear-gradient for instance), I don't really know how the gutter decorations behaves in that so I'll have to take some time to make experiments.

I can't promise it'll be available soon, but I'll definitely take a look at this.

**Comment by sanusart** [comment]
Got it. Thanks for clarification.

**Comment by abe33** [comment]
@sanusart Starting with v0.19.0 you'll have access to a gutter marker type :sparkles:.

**Comment by sanusart** [comment]
:+1:  
Wonderful news @abe33 
Thank you very much!
