### ISSUE TITLE
Would support for elm be possible?

### ISSUE THREAD

**Issue by tcoopman** [abe33/atom-pigments#98]
It would be nice if this plugin could support elm syntax.
As you can see here http://package.elm-lang.org/packages/elm-lang/core/2.1.0/Color the syntax looks for example like: `rgba 100 100 100 1` or `rgb 255 200 150`

**Comment by abe33** [comment]
Sure, doesn't look too complicated, I'll try to find some time to implement it this week.

**Comment by tcoopman** [comment]
Thanks, would be great!
