### ISSUE TITLE
Add an option to show color swatch while cursor is inside color declaration

### ISSUE THREAD

**Issue by johnmuhl** [abe33/atom-pigments#99]
![untitled](https://cloud.githubusercontent.com/assets/7944/10438692/b815413a-70fa-11e5-9404-92e53b9f87f4.gif)

Note how the color swatches disappear when the cursor is within "aqua" or "pink".

**Comment by abe33** [comment]
It's an omission on my end, only background markers should disappear when the cursor intersects their range. The fix will come soon.
